#ifndef REPOSITORY2016_C
#define REPOSITORY2016_C
//This is autogenerated by convertrepositorytocfile.py!
typedef struct {
	const GUID* const guid;
	const char* const name;
} guid_name_struct;

const GUID questitem0guid = {0x01048280,0x0358,0x4f0a,0x95,0xb7,0x1f,0x9f,0x66,0x5c,0x16,0x48};
const char questitem0name[] = "Insecticide";
const GUID questitem1guid = {0x043470c5,0x6363,0x4105,0xa6,0x40,0x2c,0x7f,0xdd,0x56,0x23,0xbe};
const char questitem1name[] = "QUESTITEM Queensuite documents";
const GUID questitem2guid = {0x049ee3c9,0xb504,0x4e2d,0x9e,0x7e,0x67,0x4e,0x57,0xd8,0xe4,0xec};
const char questitem2name[] = "QUESTITEM Faulty studio microphone";
const GUID questitem3guid = {0x0534286f,0x22a0,0x45de,0x89,0x64,0xdd,0xd4,0x4d,0x6f,0x0c,0x5f};
const char questitem3name[] = "Invitation_ShishaCafe";
const GUID questitem4guid = {0x077a5a44,0xf387,0x410e,0xbf,0x23,0x7b,0xa7,0x0a,0xe3,0x1c,0x37};
const char questitem4name[] = "Keycard (FX Truck)";
const GUID questitem5guid = {0x07e878f8,0xd245,0x4cad,0xa3,0xc2,0x34,0xbb,0xbd,0x9a,0xec,0xb8};
const char questitem5name[] = "Keycard (Embassy)";
const GUID questitem6guid = {0x09badac0,0x685a,0x4bc1,0xba,0x57,0x2a,0x88,0xb9,0xe0,0x21,0x87};
const char questitem6name[] = "Marrakech_ExitKey_ArmyTruck";
const GUID questitem7guid = {0x0c3c1e88,0xca1b,0x42ae,0x91,0x28,0x06,0x4b,0x73,0x5b,0x0e,0xec};
const char questitem7name[] = "Questitem Strandberg's safe combination";
const GUID questitem8guid = {0x1374a658,0x91d2,0x4abd,0xb3,0x39,0x28,0xc7,0x83,0x54,0x67,0xe8};
const char questitem8name[] = "Poisonable_RedwineGlass";
const GUID questitem9guid = {0x15653552,0xae76,0x4a41,0x87,0xcc,0x48,0xe6,0xe3,0xf7,0xbf,0xec};
const char questitem9name[] = "Joint (Colorado)";
const GUID questitem10guid = {0x185121e3,0xa89b,0x43b8,0x9e,0x4f,0xd9,0xb5,0xe2,0x46,0x74,0x2b};
const char questitem10name[] = "Payphone_Manual";
const GUID questitem11guid = {0x195dcd6b,0x6663,0x4768,0x9e,0x0a,0xc9,0x4e,0x24,0x4c,0xbe,0xa4};
const char questitem11name[] = "Vodka Bottle";
const GUID questitem12guid = {0x1eced699,0x6063,0x4d3e,0xb5,0xcb,0x9c,0xcb,0x24,0x4d,0x8c,0xd2};
const char questitem12name[] = "The Last Word PDA";
const GUID questitem13guid = {0x2092f606,0xe9e5,0x4525,0xbe,0x09,0x9b,0x4d,0x6b,0x59,0x7f,0x2c};
const char questitem13name[] = "Marrakech_Key_Old_School_Gate";
const GUID questitem14guid = {0x21651516,0x90a3,0x4a02,0xbc,0x8b,0x60,0x0b,0xeb,0x15,0x36,0x84};
const char questitem14name[] = "Invitation_Marrakech_MembersClub";
const GUID questitem15guid = {0x22f8ffdb,0x073d,0x48a1,0xab,0xb9,0x13,0x07,0x58,0x00,0x00,0x8e};
const char questitem15name[] = "QuestItem_Italy_DNAVirus_Francesca";
const GUID questitem16guid = {0x27f09df0,0x93ac,0x4222,0xa5,0x46,0xf6,0x0d,0x7a,0xf8,0xb5,0xf6};
const char questitem16name[] = "Key (Cultist Apartment)";
const GUID questitem17guid = {0x2ad76caf,0x8af3,0x44b1,0x90,0x4b,0xfd,0x99,0xb2,0x35,0x50,0xf1};
const char questitem17name[] = "Key (Palace Master)";
const GUID questitem18guid = {0x2c73eb46,0xeafc,0x42a2,0x82,0x88,0xe1,0x87,0xa0,0x64,0x1f,0xc7};
const char questitem18name[] = "Pilsner_phone_A";
const GUID questitem19guid = {0x2cac278e,0x49a1,0x47d7,0x89,0x3e,0xec,0xc9,0x8f,0x35,0xa7,0x39};
const char questitem19name[] = "Exit Key (Speedboat)";
const GUID questitem20guid = {0x2cff2cd2,0xa2a6,0x4b6c,0xa0,0xd3,0xad,0x01,0x0f,0x0c,0xf8,0x21};
const char questitem20name[] = "Key (Courtyard)";
const GUID questitem21guid = {0x350949dd,0x941e,0x4c7f,0xb7,0x85,0xbd,0x4f,0x4f,0x13,0x62,0x29};
const char questitem21name[] = "Key_(Town Hall)";
const GUID questitem22guid = {0x362ceb48,0xa540,0x4472,0x8f,0xbf,0xdf,0xea,0xf7,0xec,0xd9,0xc4};
const char questitem22name[] = "Questitem stemcell transfusion manual";
const GUID questitem23guid = {0x39666cab,0xf6cc,0x4bb2,0x8e,0x21,0x39,0xe0,0xb3,0xea,0xb9,0x1c};
const char questitem23name[] = "Vodka Bottle (ZIKA)";
const GUID questitem24guid = {0x3b65524a,0x0b68,0x4d17,0x84,0x1b,0x22,0x1c,0x1e,0x63,0x75,0x60};
const char questitem24name[] = "Poisonable_ChampagneGlass";
const GUID questitem25guid = {0x40ef4d5b,0x88a2,0x4d09,0xbd,0x24,0xb5,0x22,0x15,0x33,0x1b,0x6f};
const char questitem25name[] = "Kremlin Note";
const GUID questitem26guid = {0x434eb73c,0xbdd4,0x47ed,0xb1,0xd6,0x57,0xac,0xc4,0xef,0xc3,0xf7};
const char questitem26name[] = "Pack of cigarettes";
const GUID questitem27guid = {0x46565e1c,0x8fd8,0x42d2,0xbc,0xa1,0x7e,0xc1,0x89,0x2b,0x23,0xc6};
const char questitem27name[] = "Marrakech_ExitKey_DeliveryTruck";
const GUID questitem28guid = {0x47b73874,0xcb09,0x4b67,0x82,0x0b,0xb7,0x2c,0xec,0x27,0xd8,0xcd};
const char questitem28name[] = "Watch_Blueprint";
const GUID questitem29guid = {0x48f0f3c6,0xda62,0x4f49,0xa1,0x7a,0xf6,0x09,0x6f,0xd9,0x51,0xb4};
const char questitem29name[] = "Phone_Helmut";
const GUID questitem30guid = {0x49a75181,0x0d19,0x4f95,0xbf,0xa9,0x76,0xe1,0x2e,0x1d,0xb2,0xb0};
const char questitem30name[] = "Art Replica";
const GUID questitem31guid = {0x49c5edfa,0xbd1c,0x4914,0x83,0x68,0xba,0xc3,0xb6,0x5b,0xec,0xf1};
const char questitem31name[] = "Bergs Drugs";
const GUID questitem32guid = {0x4a1adf8c,0x596b,0x4515,0x90,0xa5,0xb4,0x63,0x2d,0x19,0x3a,0x98};
const char questitem32name[] = "Phone_Bootycall";
const GUID questitem33guid = {0x4f2f4e60,0xd7f0,0x407b,0xb6,0x24,0xde,0x88,0x0f,0x9e,0x30,0x15};
const char questitem33name[] = "Poisonable_CoffeCup";
const GUID questitem34guid = {0x4ffc99ab,0xac92,0x429f,0xbb,0xb9,0x80,0x2e,0xcf,0x4b,0x3c,0x6c};
const char questitem34name[] = "Key (Toilet Door)";
const GUID questitem35guid = {0x50333564,0x9467,0x4310,0x8b,0x96,0x29,0x5a,0x59,0x65,0xbb,0xe7};
const char questitem35name[] = "Invitation_MuseEvent";
const GUID questitem36guid = {0x52c08c7e,0x6a63,0x414d,0xb7,0x47,0x39,0xb4,0xfb,0xe8,0xfa,0x06};
const char questitem36name[] = "Interpol_Badge";
const GUID questitem37guid = {0x55d34557,0x5b46,0x422f,0x84,0xce,0x7b,0xb1,0x3c,0xfc,0xef,0x96};
const char questitem37name[] = "Auction Password Dongle";
const GUID questitem38guid = {0x5761d4f2,0xee0d,0x4b8f,0x8d,0xf4,0xdf,0xd7,0xbd,0xa2,0x3a,0x24};
const char questitem38name[] = "Hokkaido_ExitKey_SnowMobile";
const GUID questitem39guid = {0x592dfc11,0x1018,0x4b5d,0x87,0xc2,0x7e,0x0d,0xf1,0xdb,0xea,0xa5};
const char questitem39name[] = "Key (Bosco's Trailer)";
const GUID questitem40guid = {0x5afc47f4,0xdf09,0x435c,0xae,0x62,0x6a,0x30,0xae,0x42,0x58,0x1f};
const char questitem40name[] = "Phone_BoscosAgent";
const GUID questitem41guid = {0x5c7474ad,0xd245,0x43ca,0x94,0x8d,0x88,0x00,0xb2,0x32,0x4e,0x8c};
const char questitem41name[] = "Lethal fugu fish";
const GUID questitem42guid = {0x5d6501e0,0x4e35,0x432e,0x92,0x43,0xe3,0xdf,0x6c,0x5d,0xdb,0xd0};
const char questitem42name[] = "RFID Masterchip (Hokkaido)";
const GUID questitem43guid = {0x5d8c4c25,0x8aed,0x4ea8,0x9d,0x13,0x5f,0xde,0xa4,0x37,0x3e,0x7c};
const char questitem43name[] = "Questitem Silvio Medical Journal";
const GUID questitem44guid = {0x601e72ee,0x7d29,0x4f6d,0x86,0xa9,0x72,0x02,0x6e,0xfe,0x9c,0xd4};
const char questitem44name[] = "Invitation_FashionShow";
const GUID questitem45guid = {0x605f66ae,0xe2e0,0x4e48,0x94,0x38,0x93,0xfa,0x03,0xad,0xce,0xdf};
const char questitem45name[] = "Marrakesh_Key_MaintenanceRoom";
const GUID questitem46guid = {0x6410cb8e,0xc8be,0x47d6,0xad,0x88,0x8c,0x18,0x1c,0x4a,0x31,0x83};
const char questitem46name[] = "QuestItem_ExplosiveCompound";
const GUID questitem47guid = {0x6526cae3,0xe7e0,0x4977,0x80,0x04,0xf3,0x40,0x02,0x01,0xc2,0x9e};
const char questitem47name[] = "Key (Militia Master)";
const GUID questitem48guid = {0x6615e074,0x9017,0x46a8,0xb8,0xa7,0x9a,0xf7,0x03,0x46,0xa7,0xb3};
const char questitem48name[] = "Key (Basement)";
const GUID questitem49guid = {0x6659df4c,0x0a18,0x4eff,0x8b,0x0e,0xa0,0x87,0x38,0x4e,0x1e,0xbc};
const char questitem49name[] = "Bosco Car Key";
const GUID questitem50guid = {0x66632ec7,0x5782,0x4189,0x85,0x68,0x59,0xb7,0xe9,0x5f,0xff,0xe3};
const char questitem50name[] = "Key (Negroni Snail Key)";
const GUID questitem51guid = {0x6975834b,0xf1eb,0x470d,0xa8,0xbd,0x2c,0x41,0x9d,0xa9,0x9a,0xb6};
const char questitem51name[] = "Key (Assistant Apartment)";
const GUID questitem52guid = {0x69a0f24a,0x7844,0x495c,0x95,0x92,0x0d,0xad,0xfc,0x11,0x81,0xbf};
const char questitem52name[] = "Questitem neurochip manual";
const GUID questitem53guid = {0x69f843a8,0x320d,0x47cf,0xac,0x96,0xe9,0xeb,0xba,0x06,0x41,0x5f};
const char questitem53name[] = "Keycard_Bangkok_SkeletonKey";
const GUID questitem54guid = {0x6a1ba1bf,0x8a02,0x4c08,0x84,0xc9,0x4d,0xe2,0x6b,0xc5,0x49,0x44};
const char questitem54name[] = "Poisonable_RedwineBottle";
const GUID questitem55guid = {0x6c05ffd3,0xa02b,0x45b6,0x9c,0x05,0xac,0x3f,0x6f,0xcc,0x05,0x61};
const char questitem55name[] = "Lumumba Memory Stick";
const GUID questitem56guid = {0x6cae7694,0x0a60,0x4a13,0xab,0x3e,0x63,0x62,0x40,0x04,0x18,0x5e};
const char questitem56name[] = "Bodyguard_Phone";
const GUID questitem57guid = {0x6d2bfbdb,0x9d5d,0x41b1,0x90,0x74,0x27,0x00,0x86,0xba,0x91,0x7c};
const char questitem57name[] = "Key (Oldtown House)";
const GUID questitem58guid = {0x70380111,0x10f5,0x475e,0x8e,0x3e,0xc4,0xa0,0x7e,0x93,0x0b,0x59};
const char questitem58name[] = "Movieset Blank Ammo";
const GUID questitem59guid = {0x70b23b30,0x1a99,0x4f93,0xaf,0xdf,0xfe,0xe6,0xb8,0xc4,0x8a,0x77};
const char questitem59name[] = "Penthouse safe combination";
const GUID questitem60guid = {0x716b351a,0x1e2e,0x4b12,0xb4,0x05,0xb0,0x30,0x76,0x3f,0x30,0x1e};
const char questitem60name[] = "Key (ICA safehouse)";
const GUID questitem61guid = {0x74a4f6ee,0xb465,0x437c,0xbe,0xf9,0x3a,0x67,0xc9,0x93,0x28,0x53};
const char questitem61name[] = "Python_Documents";
const GUID questitem62guid = {0x75323d28,0x492d,0x4952,0x9f,0xcf,0xa0,0xef,0xf9,0x43,0x69,0x5c};
const char questitem62name[] = "Key (Berg's Garage)";
const GUID questitem63guid = {0x7597e4c5,0xaeed,0x40da,0x96,0x41,0x98,0x7e,0x39,0x08,0x91,0x57};
const char questitem63name[] = "Marrakech_Key_Members_Club";
const GUID questitem64guid = {0x77ec0604,0x4e35,0x4c9b,0xab,0x72,0x55,0x12,0xed,0x44,0x94,0x2b};
const char questitem64name[] = "Questitem gama pamphlet";
const GUID questitem65guid = {0x812bd23b,0x4998,0x4fb8,0x86,0x25,0x1b,0x7b,0xad,0xec,0x27,0x46};
const char questitem65name[] = "Poisonable_BeerBottle";
const GUID questitem66guid = {0x83f4fb3f,0xf8f4,0x47dd,0x94,0xe6,0x1f,0x46,0x82,0x7f,0x8d,0x28};
const char questitem66name[] = "QUESTITEM Colorado Limo documents";
const GUID questitem67guid = {0x8521184b,0x4899,0x4e63,0xb9,0xd0,0xe0,0xbf,0x83,0x07,0x06,0xa3};
const char questitem67name[] = "QuestItem The Author Virus Sample";
const GUID questitem68guid = {0x85d5b66f,0xce1d,0x4b73,0xac,0xac,0x3d,0xf1,0x82,0x49,0x6b,0xb6};
const char questitem68name[] = "Key (Printing Storage Room)";
const GUID questitem69guid = {0x87d60de1,0xc050,0x48a1,0xba,0x43,0x9d,0x2d,0xbc,0x05,0x2d,0xe0};
const char questitem69name[] = "Diamond Bag";
const GUID questitem70guid = {0x88a02bfd,0xee50,0x4d83,0x8a,0x37,0xb4,0xeb,0xa5,0xe8,0x8c,0xb3};
const char questitem70name[] = "Key (Shop)";
const GUID questitem71guid = {0x89785a8e,0xb2eb,0x45aa,0x96,0x1c,0xdb,0xfb,0xfe,0xfe,0xd9,0x62};
const char questitem71name[] = "Poisonable_WhitewineBottle";
const GUID questitem72guid = {0x8afd1f29,0x6a94,0x4b45,0xa3,0xa0,0xe3,0x61,0x85,0xb4,0x1b,0x23};
const char questitem72name[] = "Poisonable_CocktailGlass";
const GUID questitem73guid = {0x8b211b88,0x4e36,0x436b,0xbf,0x17,0xdf,0x0c,0xd5,0x86,0xd4,0x9a};
const char questitem73name[] = "Italy_ExitKey_StaffCar";
const GUID questitem74guid = {0x8d21a3fa,0x784c,0x4cb6,0x91,0x72,0xb9,0xe9,0x0f,0x39,0x20,0xc4};
const char questitem74name[] = "Keycard (Secure Attic Room)";
const GUID questitem75guid = {0x8de2b288,0x489b,0x4778,0xaf,0x8c,0xf6,0xb3,0xe6,0xf8,0x44,0x13};
const char questitem75name[] = "Negroni PDA";
const GUID questitem76guid = {0x8ffa3b1f,0x7989,0x4dbb,0x81,0xdb,0x2b,0xdc,0xbe,0x0c,0xc3,0x16};
const char questitem76name[] = "Invitation_TheLastWord_BookReading";
const GUID questitem77guid = {0x90f54148,0x45dd,0x4959,0x9d,0x80,0x77,0x64,0xb4,0x52,0xe8,0x5e};
const char questitem77name[] = "Poisonable_WhitewineGlass";
const GUID questitem78guid = {0x92685c54,0x259f,0x417f,0x89,0xa0,0x95,0x94,0x2e,0x42,0xa0,0x57};
const char questitem78name[] = "Questitem BioLab Security Protocol";
const GUID questitem79guid = {0x927ed0d3,0x830b,0x48fc,0x87,0x54,0x8a,0x8f,0xc3,0xfc,0xcb,0x2b};
const char questitem79name[] = "Grave Flowers";
const GUID questitem80guid = {0x92a71bd8,0x471e,0x49c9,0xb6,0x98,0x16,0x77,0x11,0x21,0xac,0x05};
const char questitem80name[] = "Flirtini Ledger";
const GUID questitem81guid = {0x93a7d4ac,0xc8a8,0x433f,0xb7,0xc4,0x26,0x79,0x16,0xa4,0xf4,0x36};
const char questitem81name[] = "QuestItem Francesca DNA Sample";
const GUID questitem82guid = {0x9526229d,0xb205,0x42ee,0xa7,0x54,0xc1,0x35,0xad,0xf0,0x97,0x50};
const char questitem82name[] = "Poisonable_ChampagneBottle";
const GUID questitem83guid = {0x968f4648,0xbbfc,0x4f03,0xbc,0xc2,0xa7,0x53,0x98,0xd7,0x1a,0xf3};
const char questitem83name[] = "Questitem patient journal b";
const GUID questitem84guid = {0x9712eaaa,0x43b7,0x4327,0xbd,0x04,0x7f,0x73,0x1a,0x08,0xa3,0xb3};
const char questitem84name[] = "Camera Lens";
const GUID questitem85guid = {0x97f976fe,0x2f6e,0x4539,0xb9,0x29,0x84,0xd8,0x65,0x65,0x3c,0x75};
const char questitem85name[] = "Key (Rose's Room)";
const GUID questitem86guid = {0x980a20ab,0x2786,0x4191,0xaa,0xeb,0x1c,0xba,0x98,0x46,0x0a,0xf8};
const char questitem86name[] = "Detectives Phone";
const GUID questitem87guid = {0x9877d2fb,0x9685,0x41e7,0x88,0x12,0x2a,0xec,0xfc,0xe2,0x71,0xb7};
const char questitem87name[] = "Bangkok exit key tuk tuk";
const GUID questitem88guid = {0x9ce93fdf,0x95fb,0x48a2,0x92,0x0a,0xf7,0x37,0xcc,0x8b,0x4c,0x61};
const char questitem88name[] = "QUESTITEM Silvio's family video";
const GUID questitem89guid = {0xa40d4507,0x2af0,0x41a4,0xa4,0xf4,0xb6,0xd8,0x25,0xe0,0x34,0x26};
const char questitem89name[] = "Bangkok Questitem Cake Figurehead";
const GUID questitem90guid = {0xa42a9432,0x8af3,0x4702,0xab,0xc3,0x17,0xb8,0x8a,0x3c,0xb5,0xb7};
const char questitem90name[] = "Poisonable_VodkaGlass";
const GUID questitem91guid = {0xa52943f8,0xc602,0x418c,0x91,0xbd,0xb5,0x04,0x93,0x29,0xcf,0xd8};
const char questitem91name[] = "Key_(Sewer)";
const GUID questitem92guid = {0xa61d0f7d,0xf4dc,0x4fe2,0xa5,0xc3,0xb9,0x0c,0x71,0x20,0x66,0x42};
const char questitem92name[] = "Keycard_Bangkok_2A_WingB";
const GUID questitem93guid = {0xa717aced,0x4f86,0x4fcd,0x9b,0x5e,0xd6,0x69,0x17,0x3a,0xb9,0xd1};
const char questitem93name[] = "ICON Action Figure";
const GUID questitem94guid = {0xa719b63b,0x7a5d,0x4cf3,0xab,0xfd,0x2e,0xf5,0x1d,0xea,0xbc,0xb2};
const char questitem94name[] = "Questitem Exposive Test Memo";
const GUID questitem95guid = {0xa729d2c1,0xd89c,0x4da8,0xa6,0x28,0x81,0x6b,0xa8,0x7d,0xc3,0x49};
const char questitem95name[] = "Poisonable_WaterCup";
const GUID questitem96guid = {0xa7f468a1,0xfae6,0x48f0,0xaa,0xdf,0xcb,0x4a,0xa4,0xba,0x04,0x4d};
const char questitem96name[] = "Virus Vial";
const GUID questitem97guid = {0xa9debd40,0x0840,0x4d44,0xa0,0x35,0x47,0x72,0x95,0xf3,0xd0,0x01};
const char questitem97name[] = "Key (Fuel case)";
const GUID questitem98guid = {0xab302531,0xd24a,0x4770,0xae,0x14,0xfd,0x9e,0xf4,0x0f,0xb1,0x1b};
const char questitem98name[] = "Biolab Password Dongle";
const GUID questitem99guid = {0xabba50a7,0xd87e,0x418a,0xaa,0x36,0xfa,0x9c,0x3e,0x91,0x5b,0x6d};
const char questitem99name[] = "Body Storage Area Key";
const GUID questitem100guid = {0xac1f44ac,0x0542,0x4e3e,0x98,0x05,0x81,0xce,0xeb,0x49,0x98,0x04};
const char questitem100name[] = "Joint";
const GUID questitem101guid = {0xac77e98d,0x4ffa,0x4755,0x80,0xfc,0xcd,0x6e,0x7a,0xdc,0x63,0xfb};
const char questitem101name[] = "Expired Canned Bolognese (Sick)";
const GUID questitem102guid = {0xac849e49,0xf0b4,0x4d79,0xac,0x18,0xa5,0x2a,0x05,0x0a,0xbe,0x0e};
const char questitem102name[] = "Key (Ruin Entrance)";
const GUID questitem103guid = {0xaf40b2b8,0x2861,0x4e98,0x8e,0x8f,0xc1,0x23,0x14,0xd4,0xf0,0x4f};
const char questitem103name[] = "Stem_Cells";
const GUID questitem104guid = {0xaf8a7b6c,0x692c,0x4a76,0xb9,0xbc,0x2b,0x91,0xce,0x32,0xbc,0xbc};
const char questitem104name[] = "Nitroglycerin";
const GUID questitem105guid = {0xb48bc55e,0xaaf7,0x4c62,0x9f,0xbd,0x07,0xba,0xe9,0xb8,0xe2,0x2b};
const char questitem105name[] = "QUESTITEM Holiday Present";
const GUID questitem106guid = {0xb541d1ce,0x3e7a,0x49bb,0xb3,0xae,0xf5,0xa6,0xca,0x44,0x12,0x39};
const char questitem106name[] = "Camera";
const GUID questitem107guid = {0xb646c5a3,0x05d7,0x424c,0x82,0x65,0xc5,0x42,0xcd,0x56,0xc0,0x2a};
const char questitem107name[] = "Questitem Silvio's safe combination";
const GUID questitem108guid = {0xb86b9ece,0xc929,0x44f6,0x89,0x03,0x8f,0x2c,0x81,0x7e,0x2a,0x19};
const char questitem108name[] = "QuestItem_CannonBall";
const GUID questitem109guid = {0xba907f07,0x49e3,0x4dcd,0x86,0xd2,0x68,0x7e,0xd3,0x4c,0xc5,0xac};
const char questitem109name[] = "Key (Perimeter Gate)";
const GUID questitem110guid = {0xbddd1165,0x2da4,0x43ba,0xa6,0x1c,0x0c,0xe9,0xec,0x3c,0x6d,0x3f};
const char questitem110name[] = "Questitem Zaydan's safe combination";
const GUID questitem111guid = {0xbe79f209,0xa9bf,0x4518,0xbb,0xc2,0x68,0x1c,0xb5,0x96,0x70,0xea};
const char questitem111name[] = "Hokkaido_ExitKey_Helicopter";
const GUID questitem112guid = {0xc50f7a57,0x9e72,0x4029,0xb6,0xf5,0x5c,0xa1,0x25,0xee,0x44,0xed};
const char questitem112name[] = "USB Kill List";
const GUID questitem113guid = {0xc55f64a2,0x8c90,0x45f6,0xb0,0x5f,0xba,0xcf,0xb9,0xba,0xe6,0x52};
const char questitem113name[] = "Abiatti_Schedule";
const GUID questitem114guid = {0xc5f4c612,0x8acc,0x47ca,0xb8,0x69,0x35,0x4b,0x03,0xa0,0x1e,0xc6};
const char questitem114name[] = "Python_BodyguardNote";
const GUID questitem115guid = {0xc8a504a7,0xc018,0x4ea6,0x86,0x25,0x09,0xd2,0x12,0x4e,0xa4,0x7c};
const char questitem115name[] = "Keycard (Mansion Entrance)";
const GUID questitem116guid = {0xc9f0b076,0x0ade,0x4795,0xb3,0xae,0x90,0x1b,0x58,0x29,0x2e,0x69};
const char questitem116name[] = "Tutorial Questitem Map Slides";
const GUID questitem117guid = {0xcc978ceb,0x74b0,0x47b4,0x94,0x16,0x89,0xb4,0x13,0xd7,0xe7,0xcc};
const char questitem117name[] = "Keycard_Bangkok_1A_WingA";
const GUID questitem118guid = {0xce67b55d,0xa0f2,0x4435,0x92,0x8d,0x4c,0x74,0x30,0xe8,0x61,0xf0};
const char questitem118name[] = "Questitem Romantic Note";
const GUID questitem119guid = {0xcf448616,0xa517,0x4e61,0xa9,0x57,0x9b,0xef,0x7f,0x97,0xcf,0x1e};
const char questitem119name[] = "Movieset Live Ammo";
const GUID questitem120guid = {0xcf6d9c6f,0x38f6,0x4dd4,0xb7,0xf7,0x60,0x10,0xd9,0xe3,0x8c,0xe2};
const char questitem120name[] = "Questitem yoga schedule";
const GUID questitem121guid = {0xd1175a69,0xf053,0x4a9c,0x95,0x53,0xc8,0x42,0x06,0x73,0x9c,0x51};
const char questitem121name[] = "Sean_Rose_Mask";
const GUID questitem122guid = {0xd12fc231,0x020b,0x4673,0xa7,0xb8,0x37,0x89,0xed,0x9f,0xee,0x93};
const char questitem122name[] = "Faberge Egg";
const GUID questitem123guid = {0xd2b33b62,0x5be1,0x4230,0xaa,0xcc,0x64,0x78,0x25,0x58,0x11,0x46};
const char questitem123name[] = "Questitem medical ai manual";
const GUID questitem124guid = {0xd34167f6,0x5171,0x411f,0x9d,0x8f,0xc8,0xdd,0x10,0x00,0x0e,0x2a};
const char questitem124name[] = "Art Real";
const GUID questitem125guid = {0xdabe2d27,0xd2a0,0x47f1,0xad,0xec,0x4a,0x2f,0x48,0xe8,0x6b,0x05};
const char questitem125name[] = "Game Changer Safe      ";
const GUID questitem126guid = {0xdccdef11,0xd43b,0x445e,0xb1,0xf0,0x34,0x7b,0x40,0x95,0x4e,0x95};
const char questitem126name[] = "Roses_Diary";
const GUID questitem127guid = {0xe1f1be10,0xace7,0x43d6,0xa6,0x73,0x23,0x14,0xe3,0x40,0x3a,0x2e};
const char questitem127name[] = "Poisonable_Water Bottle";
const GUID questitem128guid = {0xe3640fa0,0x96cf,0x4b96,0x8a,0x6d,0x6c,0xfd,0xd0,0x6b,0x27,0x81};
const char questitem128name[] = "Keycard (Mansion Lab)";
const GUID questitem129guid = {0xe3c6d2b2,0x164c,0x4d3f,0x82,0xe4,0xf0,0xcd,0xba,0x62,0x72,0x6d};
const char questitem129name[] = "WalkieTalkie_Marrakesh";
const GUID questitem130guid = {0xe45c295d,0x60dd,0x4cba,0xa0,0x1b,0x0d,0xc1,0xb6,0xf1,0xb1,0x7c};
const char questitem130name[] = "Experimental medicine";
const GUID questitem131guid = {0xe492898b,0xf1db,0x4321,0x98,0xa2,0xda,0x0e,0xe0,0xeb,0x0a,0x44};
const char questitem131name[] = "Keycard_Bangkok_Room206";
const GUID questitem132guid = {0xe56b86f9,0xdfcc,0x4525,0x80,0x73,0xcb,0x40,0x42,0x17,0x1c,0x84};
const char questitem132name[] = "Key (Carpet Shop)";
const GUID questitem133guid = {0xe59142e9,0xfd50,0x46d5,0x9a,0x34,0xcb,0x08,0x52,0xd0,0x86,0xfc};
const char questitem133name[] = "Keycard (Hokkaido Freezer)";
const GUID questitem134guid = {0xe5a9424b,0x4aba,0x4334,0xb2,0xa6,0x24,0xf5,0x69,0xa9,0xe0,0xbc};
const char questitem134name[] = "Keycard_Bangkok_1B_WingA";
const GUID questitem135guid = {0xe5aba0db,0x3683,0x41a5,0x9f,0x02,0xf8,0xe7,0xe9,0x2c,0xe6,0x06};
const char questitem135name[] = "Key (Mansion Masterkey)";
const GUID questitem136guid = {0xe5f613f8,0xf6c7,0x4d48,0x9d,0x0c,0xfe,0x90,0x36,0xfb,0x19,0x38};
const char questitem136name[] = "Sean_Biometric_Data";
const GUID questitem137guid = {0xe65953cb,0xf954,0x4d21,0x9f,0x11,0x52,0xb4,0x54,0xca,0xc1,0x5e};
const char questitem137name[] = "QuestItem_GunPowder_Pouch";
const GUID questitem138guid = {0xe757a3de,0xa6f7,0x4604,0x8e,0x6c,0xd8,0xf9,0x4c,0xce,0xc8,0x33};
const char questitem138name[] = "VIP Capsule Key";
const GUID questitem139guid = {0xe7a4c4e1,0x6d42,0x4e0a,0x80,0x47,0xaf,0x22,0x1c,0x6f,0xc0,0xb3};
const char questitem139name[] = "Key (Church Entrance)";
const GUID questitem140guid = {0xe80b2d45,0x6c46,0x4f3d,0x83,0x28,0xd2,0x4c,0xd6,0x25,0x1d,0xb4};
const char questitem140name[] = "Pilsner_Phone_B";
const GUID questitem141guid = {0xe94bcd93,0x6bac,0x4132,0xba,0xfd,0x25,0xa1,0x03,0x22,0x9b,0x10};
const char questitem141name[] = "Wine_Reservation";
const GUID questitem142guid = {0xea02922a,0xb33f,0x492a,0xa4,0xb9,0x07,0xd1,0x86,0x6d,0x8d,0xb5};
const char questitem142name[] = "Questitem Murder evidence memory stick";
const GUID questitem143guid = {0xee25fc91,0xe42e,0x4044,0x99,0xb4,0xb3,0xc4,0x20,0x6d,0x25,0x0d};
const char questitem143name[] = "Exploding_Watch_Battery";
const GUID questitem144guid = {0xef12566c,0x80ff,0x41ac,0xb9,0xe8,0x19,0xcd,0x43,0xe7,0xd4,0x20};
const char questitem144name[] = "Marrakech_ExitKey_EmbassyStaffCar";
const GUID questitem145guid = {0xefe40b4b,0xab5c,0x4d49,0x92,0x9e,0xf6,0x4c,0x36,0xfe,0x4a,0x26};
const char questitem145name[] = "Colorado_ExitKey_QuadBike";
const GUID questitem146guid = {0xf08fd103,0xa10f,0x47fa,0x93,0x33,0x00,0xd1,0xe3,0x5d,0xb0,0x46};
const char questitem146name[] = "Bosco Trailer key";
const GUID questitem147guid = {0xf174ec0e,0xda7a,0x46be,0x92,0x0a,0x78,0x2e,0xca,0xf6,0x5c,0xbc};
const char questitem147name[] = "Poisonable_FoodPlate";
const GUID questitem148guid = {0xf24b59f9,0x70ca,0x4b92,0xb4,0xe5,0x99,0x87,0xdf,0xbe,0x36,0x8c};
const char questitem148name[] = "Poisonable_FoodPlate_Spaghetti";
const GUID questitem149guid = {0xf3eb8eba,0x0cdd,0x4147,0x9b,0x9b,0x55,0x1b,0x6a,0x3b,0x59,0x00};
const char questitem149name[] = "Key (Oldtown Shop)";
const GUID questitem150guid = {0xf4b85a73,0x245f,0x49ed,0xb6,0xf0,0x6e,0x45,0x0c,0x64,0xd0,0x5e};
const char questitem150name[] = "Questitem patient journal a";
const GUID questitem151guid = {0xf8b7e382,0x6893,0x48b5,0xb3,0x4e,0xae,0xc6,0x68,0xd2,0x05,0x64};
const char questitem151name[] = "Guest List";
const GUID questitem152guid = {0xfa8837e1,0xed10,0x4201,0xad,0x5a,0x6a,0x33,0x63,0x01,0x54,0x7b};
const char questitem152name[] = "Keycard_Bangkok_Managers_Office";
const GUID questitem153guid = {0x915275e4,0xe36f,0x4819,0x88,0x20,0x37,0xf0,0x4b,0x32,0x06,0x59};
const char questitem153name[] = "Sean_Rose_Watch";
const char questitem[] = "questitem";
#define questitemARRLEN 154
guid_name_struct questitem_guid_name[questitemARRLEN] = {
	(const GUID* const)&questitem0guid, (const char* const)&questitem0name,
	(const GUID* const)&questitem1guid, (const char* const)&questitem1name,
	(const GUID* const)&questitem2guid, (const char* const)&questitem2name,
	(const GUID* const)&questitem3guid, (const char* const)&questitem3name,
	(const GUID* const)&questitem4guid, (const char* const)&questitem4name,
	(const GUID* const)&questitem5guid, (const char* const)&questitem5name,
	(const GUID* const)&questitem6guid, (const char* const)&questitem6name,
	(const GUID* const)&questitem7guid, (const char* const)&questitem7name,
	(const GUID* const)&questitem8guid, (const char* const)&questitem8name,
	(const GUID* const)&questitem9guid, (const char* const)&questitem9name,
	(const GUID* const)&questitem10guid, (const char* const)&questitem10name,
	(const GUID* const)&questitem11guid, (const char* const)&questitem11name,
	(const GUID* const)&questitem12guid, (const char* const)&questitem12name,
	(const GUID* const)&questitem13guid, (const char* const)&questitem13name,
	(const GUID* const)&questitem14guid, (const char* const)&questitem14name,
	(const GUID* const)&questitem15guid, (const char* const)&questitem15name,
	(const GUID* const)&questitem16guid, (const char* const)&questitem16name,
	(const GUID* const)&questitem17guid, (const char* const)&questitem17name,
	(const GUID* const)&questitem18guid, (const char* const)&questitem18name,
	(const GUID* const)&questitem19guid, (const char* const)&questitem19name,
	(const GUID* const)&questitem20guid, (const char* const)&questitem20name,
	(const GUID* const)&questitem21guid, (const char* const)&questitem21name,
	(const GUID* const)&questitem22guid, (const char* const)&questitem22name,
	(const GUID* const)&questitem23guid, (const char* const)&questitem23name,
	(const GUID* const)&questitem24guid, (const char* const)&questitem24name,
	(const GUID* const)&questitem25guid, (const char* const)&questitem25name,
	(const GUID* const)&questitem26guid, (const char* const)&questitem26name,
	(const GUID* const)&questitem27guid, (const char* const)&questitem27name,
	(const GUID* const)&questitem28guid, (const char* const)&questitem28name,
	(const GUID* const)&questitem29guid, (const char* const)&questitem29name,
	(const GUID* const)&questitem30guid, (const char* const)&questitem30name,
	(const GUID* const)&questitem31guid, (const char* const)&questitem31name,
	(const GUID* const)&questitem32guid, (const char* const)&questitem32name,
	(const GUID* const)&questitem33guid, (const char* const)&questitem33name,
	(const GUID* const)&questitem34guid, (const char* const)&questitem34name,
	(const GUID* const)&questitem35guid, (const char* const)&questitem35name,
	(const GUID* const)&questitem36guid, (const char* const)&questitem36name,
	(const GUID* const)&questitem37guid, (const char* const)&questitem37name,
	(const GUID* const)&questitem38guid, (const char* const)&questitem38name,
	(const GUID* const)&questitem39guid, (const char* const)&questitem39name,
	(const GUID* const)&questitem40guid, (const char* const)&questitem40name,
	(const GUID* const)&questitem41guid, (const char* const)&questitem41name,
	(const GUID* const)&questitem42guid, (const char* const)&questitem42name,
	(const GUID* const)&questitem43guid, (const char* const)&questitem43name,
	(const GUID* const)&questitem44guid, (const char* const)&questitem44name,
	(const GUID* const)&questitem45guid, (const char* const)&questitem45name,
	(const GUID* const)&questitem46guid, (const char* const)&questitem46name,
	(const GUID* const)&questitem47guid, (const char* const)&questitem47name,
	(const GUID* const)&questitem48guid, (const char* const)&questitem48name,
	(const GUID* const)&questitem49guid, (const char* const)&questitem49name,
	(const GUID* const)&questitem50guid, (const char* const)&questitem50name,
	(const GUID* const)&questitem51guid, (const char* const)&questitem51name,
	(const GUID* const)&questitem52guid, (const char* const)&questitem52name,
	(const GUID* const)&questitem53guid, (const char* const)&questitem53name,
	(const GUID* const)&questitem54guid, (const char* const)&questitem54name,
	(const GUID* const)&questitem55guid, (const char* const)&questitem55name,
	(const GUID* const)&questitem56guid, (const char* const)&questitem56name,
	(const GUID* const)&questitem57guid, (const char* const)&questitem57name,
	(const GUID* const)&questitem58guid, (const char* const)&questitem58name,
	(const GUID* const)&questitem59guid, (const char* const)&questitem59name,
	(const GUID* const)&questitem60guid, (const char* const)&questitem60name,
	(const GUID* const)&questitem61guid, (const char* const)&questitem61name,
	(const GUID* const)&questitem62guid, (const char* const)&questitem62name,
	(const GUID* const)&questitem63guid, (const char* const)&questitem63name,
	(const GUID* const)&questitem64guid, (const char* const)&questitem64name,
	(const GUID* const)&questitem65guid, (const char* const)&questitem65name,
	(const GUID* const)&questitem66guid, (const char* const)&questitem66name,
	(const GUID* const)&questitem67guid, (const char* const)&questitem67name,
	(const GUID* const)&questitem68guid, (const char* const)&questitem68name,
	(const GUID* const)&questitem69guid, (const char* const)&questitem69name,
	(const GUID* const)&questitem70guid, (const char* const)&questitem70name,
	(const GUID* const)&questitem71guid, (const char* const)&questitem71name,
	(const GUID* const)&questitem72guid, (const char* const)&questitem72name,
	(const GUID* const)&questitem73guid, (const char* const)&questitem73name,
	(const GUID* const)&questitem74guid, (const char* const)&questitem74name,
	(const GUID* const)&questitem75guid, (const char* const)&questitem75name,
	(const GUID* const)&questitem76guid, (const char* const)&questitem76name,
	(const GUID* const)&questitem77guid, (const char* const)&questitem77name,
	(const GUID* const)&questitem78guid, (const char* const)&questitem78name,
	(const GUID* const)&questitem79guid, (const char* const)&questitem79name,
	(const GUID* const)&questitem80guid, (const char* const)&questitem80name,
	(const GUID* const)&questitem81guid, (const char* const)&questitem81name,
	(const GUID* const)&questitem82guid, (const char* const)&questitem82name,
	(const GUID* const)&questitem83guid, (const char* const)&questitem83name,
	(const GUID* const)&questitem84guid, (const char* const)&questitem84name,
	(const GUID* const)&questitem85guid, (const char* const)&questitem85name,
	(const GUID* const)&questitem86guid, (const char* const)&questitem86name,
	(const GUID* const)&questitem87guid, (const char* const)&questitem87name,
	(const GUID* const)&questitem88guid, (const char* const)&questitem88name,
	(const GUID* const)&questitem89guid, (const char* const)&questitem89name,
	(const GUID* const)&questitem90guid, (const char* const)&questitem90name,
	(const GUID* const)&questitem91guid, (const char* const)&questitem91name,
	(const GUID* const)&questitem92guid, (const char* const)&questitem92name,
	(const GUID* const)&questitem93guid, (const char* const)&questitem93name,
	(const GUID* const)&questitem94guid, (const char* const)&questitem94name,
	(const GUID* const)&questitem95guid, (const char* const)&questitem95name,
	(const GUID* const)&questitem96guid, (const char* const)&questitem96name,
	(const GUID* const)&questitem97guid, (const char* const)&questitem97name,
	(const GUID* const)&questitem98guid, (const char* const)&questitem98name,
	(const GUID* const)&questitem99guid, (const char* const)&questitem99name,
	(const GUID* const)&questitem100guid, (const char* const)&questitem100name,
	(const GUID* const)&questitem101guid, (const char* const)&questitem101name,
	(const GUID* const)&questitem102guid, (const char* const)&questitem102name,
	(const GUID* const)&questitem103guid, (const char* const)&questitem103name,
	(const GUID* const)&questitem104guid, (const char* const)&questitem104name,
	(const GUID* const)&questitem105guid, (const char* const)&questitem105name,
	(const GUID* const)&questitem106guid, (const char* const)&questitem106name,
	(const GUID* const)&questitem107guid, (const char* const)&questitem107name,
	(const GUID* const)&questitem108guid, (const char* const)&questitem108name,
	(const GUID* const)&questitem109guid, (const char* const)&questitem109name,
	(const GUID* const)&questitem110guid, (const char* const)&questitem110name,
	(const GUID* const)&questitem111guid, (const char* const)&questitem111name,
	(const GUID* const)&questitem112guid, (const char* const)&questitem112name,
	(const GUID* const)&questitem113guid, (const char* const)&questitem113name,
	(const GUID* const)&questitem114guid, (const char* const)&questitem114name,
	(const GUID* const)&questitem115guid, (const char* const)&questitem115name,
	(const GUID* const)&questitem116guid, (const char* const)&questitem116name,
	(const GUID* const)&questitem117guid, (const char* const)&questitem117name,
	(const GUID* const)&questitem118guid, (const char* const)&questitem118name,
	(const GUID* const)&questitem119guid, (const char* const)&questitem119name,
	(const GUID* const)&questitem120guid, (const char* const)&questitem120name,
	(const GUID* const)&questitem121guid, (const char* const)&questitem121name,
	(const GUID* const)&questitem122guid, (const char* const)&questitem122name,
	(const GUID* const)&questitem123guid, (const char* const)&questitem123name,
	(const GUID* const)&questitem124guid, (const char* const)&questitem124name,
	(const GUID* const)&questitem125guid, (const char* const)&questitem125name,
	(const GUID* const)&questitem126guid, (const char* const)&questitem126name,
	(const GUID* const)&questitem127guid, (const char* const)&questitem127name,
	(const GUID* const)&questitem128guid, (const char* const)&questitem128name,
	(const GUID* const)&questitem129guid, (const char* const)&questitem129name,
	(const GUID* const)&questitem130guid, (const char* const)&questitem130name,
	(const GUID* const)&questitem131guid, (const char* const)&questitem131name,
	(const GUID* const)&questitem132guid, (const char* const)&questitem132name,
	(const GUID* const)&questitem133guid, (const char* const)&questitem133name,
	(const GUID* const)&questitem134guid, (const char* const)&questitem134name,
	(const GUID* const)&questitem135guid, (const char* const)&questitem135name,
	(const GUID* const)&questitem136guid, (const char* const)&questitem136name,
	(const GUID* const)&questitem137guid, (const char* const)&questitem137name,
	(const GUID* const)&questitem138guid, (const char* const)&questitem138name,
	(const GUID* const)&questitem139guid, (const char* const)&questitem139name,
	(const GUID* const)&questitem140guid, (const char* const)&questitem140name,
	(const GUID* const)&questitem141guid, (const char* const)&questitem141name,
	(const GUID* const)&questitem142guid, (const char* const)&questitem142name,
	(const GUID* const)&questitem143guid, (const char* const)&questitem143name,
	(const GUID* const)&questitem144guid, (const char* const)&questitem144name,
	(const GUID* const)&questitem145guid, (const char* const)&questitem145name,
	(const GUID* const)&questitem146guid, (const char* const)&questitem146name,
	(const GUID* const)&questitem147guid, (const char* const)&questitem147name,
	(const GUID* const)&questitem148guid, (const char* const)&questitem148name,
	(const GUID* const)&questitem149guid, (const char* const)&questitem149name,
	(const GUID* const)&questitem150guid, (const char* const)&questitem150name,
	(const GUID* const)&questitem151guid, (const char* const)&questitem151name,
	(const GUID* const)&questitem152guid, (const char* const)&questitem152name,
	(const GUID* const)&questitem153guid, (const char* const)&questitem153name,
};

const GUID melee0guid = {0x004ecac9,0x6aee,0x4b30,0xa0,0x73,0x43,0x99,0xa9,0x45,0x35,0xd8};
const char melee0name[] = "Melee_Full_SodaCan";
const GUID melee1guid = {0x1033c25d,0x3d57,0x4c15,0xb7,0xd0,0xac,0xf3,0xb4,0x56,0x65,0xef};
const char melee1name[] = "Melee_NinjaTonfa";
const GUID melee2guid = {0x1066917f,0x2e04,0x4c54,0xb8,0xcb,0x55,0xcb,0x1d,0xcc,0x2f,0x26};
const char melee2name[] = "Melee_Shovel";
const GUID melee3guid = {0x17615866,0x32e7,0x4e1e,0x95,0x1d,0x7e,0xf2,0xad,0xa7,0x96,0xe9};
const char melee3name[] = "Melee_GolfClub";
const GUID melee4guid = {0x1a11a060,0x358c,0x4054,0x98,0xec,0xd3,0x49,0x1a,0xf1,0xd7,0xc6};
const char melee4name[] = "Melee_Fiberwire";
const GUID melee5guid = {0x1bbf0ed5,0x0515,0x4599,0xa4,0xc9,0x45,0x4c,0xe5,0x9c,0xff,0x44};
const char melee5name[] = "Melee_Cleaver";
const GUID melee6guid = {0x21152383,0x6d79,0x436c,0xb3,0x59,0x0f,0x8b,0x4f,0x5e,0xd4,0xa0};
const char melee6name[] = "Melee_Machete";
const GUID melee7guid = {0x22183fd3,0xd837,0x47c6,0x9c,0x44,0x05,0x63,0x73,0x00,0xaf,0x93};
const char melee7name[] = "Melee_Coconut";
const GUID melee8guid = {0x2add9602,0xcda7,0x43fd,0x97,0x58,0x62,0x69,0xc8,0xfb,0xb2,0x33};
const char melee8name[] = "Melee_FireAxe_Holiday_Present";
const GUID melee9guid = {0x2c037ef5,0xa01b,0x4532,0x82,0x16,0x1d,0x53,0x51,0x93,0xa8,0x37};
const char melee9name[] = "Melee_CombatKnife";
const GUID melee10guid = {0x31f36818,0x623f,0x4c92,0x89,0x2f,0xd7,0xb1,0x9b,0xb3,0x25,0xe1};
const char melee10name[] = "Melee_Bust_Hokkaido";
const GUID melee11guid = {0x369c68f7,0xcbef,0x4e45,0x83,0xc7,0x8a,0xcd,0x0d,0xc2,0xd2,0x37};
const char melee11name[] = "Melee_OldAxe";
const GUID melee12guid = {0x3a8207bb,0x84f5,0x438f,0x8f,0x30,0x5c,0x83,0xae,0xf2,0xaf,0x80};
const char melee12name[] = "Melee_Hatchet";
const GUID melee13guid = {0x3c24c96a,0x557c,0x472a,0x9d,0x71,0x1a,0x23,0x5d,0x73,0x83,0xa7};
const char melee13name[] = "Melee_Hammer";
const GUID melee14guid = {0x3dbd9ee9,0xf887,0x41bb,0x83,0xbf,0x38,0x63,0x24,0xd1,0x14,0x85};
const char melee14name[] = "Melee_CeremonialKnife";
const GUID melee15guid = {0x4dee7cd6,0xf447,0x45af,0xa9,0x0e,0xc2,0xe2,0x34,0x38,0x6d,0xc3};
const char melee15name[] = "Melee_ConcealableBaton";
const GUID melee16guid = {0x510c62c2,0x1f40,0x4a4d,0x9e,0x42,0xda,0x67,0x7b,0xd1,0x16,0xe7};
const char melee16name[] = "Melee_PoliceBaton";
const GUID melee17guid = {0x51f6ed96,0x4985,0x4d09,0x82,0x18,0xe3,0xb9,0x12,0xd0,0x25,0xb9};
const char melee17name[] = "Melee_BrandingIron";
const GUID melee18guid = {0x54f800df,0x0c14,0x4a6f,0x87,0x3f,0x16,0x49,0x7b,0x4e,0xdf,0x00};
const char melee18name[] = "Melee_Machete_Bloody";
const GUID melee19guid = {0x5631dace,0x7f4a,0x4df8,0x8e,0x97,0xb4,0x73,0x73,0xb8,0x15,0xff};
const char melee19name[] = "Melee_Katana";
const GUID melee20guid = {0x58dceb1c,0xd7db,0x41dc,0x97,0x50,0x55,0xe3,0xab,0x87,0xfd,0xf0};
const char melee20name[] = "Melee_BattleAxe";
const GUID melee21guid = {0x5cc4d1ea,0xb4fa,0x4667,0xba,0x3a,0xb6,0xe8,0x59,0xf0,0x30,0x59};
const char melee21name[] = "Melee_Brick";
const GUID melee22guid = {0x5d8ca32a,0xfe4c,0x4597,0xb0,0x74,0x51,0xe3,0x6c,0x3d,0xe8,0x98};
const char melee22name[] = "Melee_Scalpel";
const GUID melee23guid = {0x62c2ac2e,0x329e,0x4648,0x82,0x2a,0xe4,0x5a,0x29,0xa9,0x3c,0xd0};
const char melee23name[] = "Melee_AmputationKnife";
const GUID melee24guid = {0x6ecf1f15,0x453c,0x4783,0x9c,0x70,0x87,0x77,0xc8,0x39,0x34,0xd7};
const char melee24name[] = "Melee_Scissors";
const GUID melee25guid = {0x7aeb740f,0x3d60,0x4e49,0x8d,0x27,0x15,0xa9,0x80,0x67,0xce,0x9f};
const char melee25name[] = "Melee_LeadPipe";
const GUID melee26guid = {0x8d937ed4,0xdc85,0x476b,0x80,0x48,0xe9,0x6a,0x89,0x00,0xe7,0xbf};
const char melee26name[] = "Melee_ProstheticArm";
const GUID melee27guid = {0x94f52181,0xb9ec,0x4363,0xba,0xef,0xd5,0x3b,0x4e,0x42,0x4b,0x74};
const char melee27name[] = "Melee_Sabre";
const GUID melee28guid = {0x95d1c5bd,0x72de,0x4236,0x97,0xc0,0xb9,0x6f,0xc5,0xd9,0x2f,0xa8};
const char melee28name[] = "Melee_PoolBall";
const GUID melee29guid = {0x97d74fa2,0x4832,0x4186,0xa4,0x47,0xc4,0xb2,0xe3,0x7d,0x53,0x7a};
const char melee29name[] = "Melee_Bust";
const GUID melee30guid = {0x987d9c9f,0x203d,0x44d9,0xbb,0xf8,0xbf,0x70,0x3f,0x34,0x95,0x65};
const char melee30name[] = "Melee_FirePoker";
const GUID melee31guid = {0xa1495dbf,0x4ceb,0x4109,0x85,0xbd,0x0f,0xa4,0x3b,0xd6,0x54,0xc8};
const char melee31name[] = "Melee_FirePoker_Holiday_Present";
const GUID melee32guid = {0xa2c56798,0x026f,0x4d0b,0x94,0x80,0xde,0x0d,0x25,0x25,0xa1,0x19};
const char melee32name[] = "Melee_FoldingKnife";
const GUID melee33guid = {0xa42123a6,0x75ea,0x4687,0x96,0xcf,0xb0,0x99,0xa4,0x9d,0x35,0x29};
const char melee33name[] = "Melee_CrystalBall";
const GUID melee34guid = {0xa874abf0,0xcfe3,0x4e0c,0x92,0x17,0x9e,0x5b,0x67,0xf9,0x78,0xce};
const char melee34name[] = "Melee_Fiberwire Sapienza Necklace";
const GUID melee35guid = {0xa8a0c154,0xc36f,0x413e,0x8f,0x29,0xb8,0x3a,0x1b,0x7a,0x22,0xf0};
const char melee35name[] = "Propane Flask";
const GUID melee36guid = {0xa8bc4325,0x718e,0x45ba,0xb0,0xe4,0x00,0x07,0x29,0xc7,0x0c,0xe4};
const char melee36name[] = "Melee_FireAxe";
const GUID melee37guid = {0xb549ea89,0xe9cc,0x44f4,0x87,0xae,0x71,0x45,0xa7,0x06,0x00,0x28};
const char melee37name[] = "Melee_BaseballBat_Clown";
const GUID melee38guid = {0xbb635e7c,0x4e87,0x43e0,0xa4,0x6a,0x16,0xe9,0x15,0x3a,0x27,0x09};
const char melee38name[] = "Melee broken drumstick";
const GUID melee39guid = {0xc21f558b,0x2935,0x41e5,0x88,0xff,0x64,0x2e,0xb1,0x76,0x1c,0xcc};
const char melee39name[] = "Melee_BaseballBat";
const GUID melee40guid = {0xc4747fa2,0x4958,0x4a02,0x92,0x6e,0x3b,0x06,0x9c,0xf2,0x18,0xdc};
const char melee40name[] = "Melee_Modern_Hammer";
const GUID melee41guid = {0xc7296c5f,0x6c0e,0x4d52,0x98,0xcd,0xe7,0x0a,0x0d,0x32,0x9e,0x73};
const char melee41name[] = "Melee_BaseballBat_Japanese";
const GUID melee42guid = {0xc86ce2f4,0x7bd1,0x4949,0xac,0xc4,0x54,0xe5,0x42,0x8d,0x93,0x96};
const char melee42name[] = "Melee_CowboyBust";
const GUID melee43guid = {0xce633778,0x7424,0x4784,0x8b,0xc2,0xf9,0xd7,0x17,0xa2,0x37,0x09};
const char melee43name[] = "Melee_Baseball";
const GUID melee44guid = {0xce8e7099,0xe60d,0x47e8,0xbf,0xd6,0x49,0x18,0x77,0x7f,0x2c,0x8b};
const char melee44name[] = "Melee_ToyTank";
const GUID melee45guid = {0xcf4838bf,0x2417,0x4baf,0xad,0x40,0x50,0xb7,0x79,0x30,0x40,0xc6};
const char melee45name[] = "Melee_CricketBall";
const GUID melee46guid = {0xd2a7fa04,0x2cac,0x45d8,0xb6,0x96,0x47,0xc5,0x66,0xbb,0x95,0xff};
const char melee46name[] = "Melee_SappersAxe";
const GUID melee47guid = {0xd439fb64,0x8713,0x4c54,0xa3,0xf3,0x90,0x73,0x0d,0xbd,0xf3,0x70};
const char melee47name[] = "Melee_Katana_Engraved";
const GUID melee48guid = {0xd64eb5f2,0x1e9b,0x402d,0x85,0x5b,0xc7,0x14,0xcf,0xde,0x50,0xdb};
const char melee48name[] = "Melee_FireExtinguisher";
const GUID melee49guid = {0xde69ce1e,0xa24d,0x4acc,0x89,0x5f,0x4c,0x3a,0x71,0xf4,0x7b,0xa8};
const char melee49name[] = "Melee_Full_SodaCan_Japanese";
const GUID melee50guid = {0xe17172cc,0xbf70,0x4df6,0x98,0x28,0xd9,0x85,0x6b,0x1a,0x24,0xfd};
const char melee50name[] = "Melee_KitchenKnife";
const GUID melee51guid = {0xe30a5b15,0xce4d,0x41d5,0xa2,0xa5,0x08,0xde,0xc9,0xc4,0xfe,0x79};
const char melee51name[] = "Melee_HiddenBlade";
const GUID melee52guid = {0xe312a416,0x5b56,0x4cb5,0x89,0x94,0x1d,0x4b,0xc8,0x2f,0xbb,0x84};
const char melee52name[] = "Melee_CircumcisionKnife";
const GUID melee53guid = {0xe55eb9a4,0xe79c,0x43c7,0x97,0x0b,0x79,0xe9,0x4e,0x76,0x83,0xb7};
const char melee53name[] = "Melee_Shuriken";
const GUID melee54guid = {0xf1f89faf,0xa441,0x4492,0xb4,0x42,0x9a,0x92,0x3b,0x5e,0xcf,0xd1};
const char melee54name[] = "Melee_LetterOpener";
const GUID melee55guid = {0xf2a74ebc,0x8f07,0x4845,0xb4,0x21,0x23,0x39,0x98,0x8e,0x19,0x94};
const char melee55name[] = "Melee_EiffelDagger";
const GUID melee56guid = {0x7257eaa1,0xc8f3,0x4e0c,0xac,0xbf,0x74,0xf7,0x38,0x69,0xc1,0xb2};
const char melee56name[] = "Melee_EiffelClub";
const char melee[] = "melee";
#define meleeARRLEN 57
guid_name_struct melee_guid_name[meleeARRLEN] = {
	(const GUID* const)&melee0guid, (const char* const)&melee0name,
	(const GUID* const)&melee1guid, (const char* const)&melee1name,
	(const GUID* const)&melee2guid, (const char* const)&melee2name,
	(const GUID* const)&melee3guid, (const char* const)&melee3name,
	(const GUID* const)&melee4guid, (const char* const)&melee4name,
	(const GUID* const)&melee5guid, (const char* const)&melee5name,
	(const GUID* const)&melee6guid, (const char* const)&melee6name,
	(const GUID* const)&melee7guid, (const char* const)&melee7name,
	(const GUID* const)&melee8guid, (const char* const)&melee8name,
	(const GUID* const)&melee9guid, (const char* const)&melee9name,
	(const GUID* const)&melee10guid, (const char* const)&melee10name,
	(const GUID* const)&melee11guid, (const char* const)&melee11name,
	(const GUID* const)&melee12guid, (const char* const)&melee12name,
	(const GUID* const)&melee13guid, (const char* const)&melee13name,
	(const GUID* const)&melee14guid, (const char* const)&melee14name,
	(const GUID* const)&melee15guid, (const char* const)&melee15name,
	(const GUID* const)&melee16guid, (const char* const)&melee16name,
	(const GUID* const)&melee17guid, (const char* const)&melee17name,
	(const GUID* const)&melee18guid, (const char* const)&melee18name,
	(const GUID* const)&melee19guid, (const char* const)&melee19name,
	(const GUID* const)&melee20guid, (const char* const)&melee20name,
	(const GUID* const)&melee21guid, (const char* const)&melee21name,
	(const GUID* const)&melee22guid, (const char* const)&melee22name,
	(const GUID* const)&melee23guid, (const char* const)&melee23name,
	(const GUID* const)&melee24guid, (const char* const)&melee24name,
	(const GUID* const)&melee25guid, (const char* const)&melee25name,
	(const GUID* const)&melee26guid, (const char* const)&melee26name,
	(const GUID* const)&melee27guid, (const char* const)&melee27name,
	(const GUID* const)&melee28guid, (const char* const)&melee28name,
	(const GUID* const)&melee29guid, (const char* const)&melee29name,
	(const GUID* const)&melee30guid, (const char* const)&melee30name,
	(const GUID* const)&melee31guid, (const char* const)&melee31name,
	(const GUID* const)&melee32guid, (const char* const)&melee32name,
	(const GUID* const)&melee33guid, (const char* const)&melee33name,
	(const GUID* const)&melee34guid, (const char* const)&melee34name,
	(const GUID* const)&melee35guid, (const char* const)&melee35name,
	(const GUID* const)&melee36guid, (const char* const)&melee36name,
	(const GUID* const)&melee37guid, (const char* const)&melee37name,
	(const GUID* const)&melee38guid, (const char* const)&melee38name,
	(const GUID* const)&melee39guid, (const char* const)&melee39name,
	(const GUID* const)&melee40guid, (const char* const)&melee40name,
	(const GUID* const)&melee41guid, (const char* const)&melee41name,
	(const GUID* const)&melee42guid, (const char* const)&melee42name,
	(const GUID* const)&melee43guid, (const char* const)&melee43name,
	(const GUID* const)&melee44guid, (const char* const)&melee44name,
	(const GUID* const)&melee45guid, (const char* const)&melee45name,
	(const GUID* const)&melee46guid, (const char* const)&melee46name,
	(const GUID* const)&melee47guid, (const char* const)&melee47name,
	(const GUID* const)&melee48guid, (const char* const)&melee48name,
	(const GUID* const)&melee49guid, (const char* const)&melee49name,
	(const GUID* const)&melee50guid, (const char* const)&melee50name,
	(const GUID* const)&melee51guid, (const char* const)&melee51name,
	(const GUID* const)&melee52guid, (const char* const)&melee52name,
	(const GUID* const)&melee53guid, (const char* const)&melee53name,
	(const GUID* const)&melee54guid, (const char* const)&melee54name,
	(const GUID* const)&melee55guid, (const char* const)&melee55name,
	(const GUID* const)&melee56guid, (const char* const)&melee56name,
};

const GUID pistol0guid = {0x04677c7b,0x94bc,0x4a78,0x8d,0x68,0xca,0x90,0xb0,0x14,0x94,0xe6};
const char pistol0name[] = "Pistol Tactical +EXTENDED MAG +AMMO +SKIN01";
const GUID pistol1guid = {0x15291f69,0x88d0,0x4a8f,0xb3,0x1b,0x71,0x60,0x5b,0xa5,0xff,0x38};
const char pistol1name[] = "Firearms_Hero_Pistol_magnum_GOTY_Striker";
const GUID pistol2guid = {0x16e21990,0xacee,0x4414,0x98,0x8c,0x93,0x8a,0x9c,0xcf,0x07,0xf8};
const char pistol2name[] = "Pistol Light +STABLE +SKIN01";
const GUID pistol3guid = {0x214004ec,0x5c86,0x4c26,0x84,0x03,0x9e,0x83,0xa9,0xbc,0xdd,0x24};
const char pistol3name[] = "Pistol Tactical +FULLAUTO +SUPPRESSOR +SKIN01";
const GUID pistol4guid = {0x2953e9ac,0xe25b,0x41ae,0xaf,0xbf,0x4a,0x47,0xf8,0x6c,0x4f,0x54};
const char pistol4name[] = "Pistol02 NPC";
const GUID pistol5guid = {0x304fd49f,0x0624,0x4691,0x85,0x06,0x14,0x9a,0x4b,0x16,0x80,0x8e};
const char pistol5name[] = "Pistol Light +SKIN01";
const GUID pistol6guid = {0x341ba426,0xd52d,0x4ae3,0x97,0xa9,0x40,0xb9,0xb3,0x63,0x3d,0x76};
const char pistol6name[] = "Pistol Tactical +SUPPRESSOR +SKIN05";
const GUID pistol7guid = {0x3747331e,0x3aba,0x48c5,0x8b,0x34,0x94,0x21,0xaa,0x86,0x47,0xe5};
const char pistol7name[] = "Pistol Light +SUPPRESSOR +EXTENDED MAG +SKIN01";
const GUID pistol8guid = {0x42c19e41,0x747d,0x4340,0x9f,0xcf,0xf3,0x62,0x2a,0x89,0x36,0x13};
const char pistol8name[] = "Pistol Light +FULLAUTO +SKIN01";
const GUID pistol9guid = {0x55ed7196,0x2303,0x4af6,0x9f,0xa3,0x45,0xb6,0x91,0x13,0x45,0x61};
const char pistol9name[] = "Pistol01 NPC";
const GUID pistol10guid = {0x613abe5c,0x6840,0x467e,0x9a,0xc1,0x6b,0x6d,0xcb,0x1c,0xa6,0xed};
const char pistol10name[] = "Pistol Tactical +STABLE +SKIN01";
const GUID pistol11guid = {0x6bd0d4bb,0x7e91,0x46d2,0x9e,0xcf,0x72,0x4a,0xc7,0x5d,0xb1,0xa3};
const char pistol11name[] = "Pistol Tactical +EXTENDED MAG + AMMO + DAMAGE +SKIN01";
const GUID pistol12guid = {0x727c144c,0xcaac,0x4db7,0xae,0xc5,0x84,0xcd,0xf5,0xe3,0xa2,0xa0};
const char pistol12name[] = "Pistol Tactical +EXTENDED MAG + AMMO +BULLET DANCER +SKIN01";
const GUID pistol13guid = {0x73875794,0x5a86,0x410e,0x84,0xa4,0x1b,0x5b,0x2f,0x7e,0x5a,0x54};
const char pistol13name[] = "Pistol Tactical +SUPPRESSOR +SKIN01";
const GUID pistol14guid = {0x77f38825,0x123c,0x45db,0xaf,0x8b,0x71,0x6e,0x7a,0xf7,0xc6,0x36};
const char pistol14name[] = "Pistol Light +STABLE +SUPPRESSOR +SKIN01";
const GUID pistol15guid = {0x8657840d,0xe87b,0x47ed,0x8b,0x1a,0xa8,0x02,0x6e,0x04,0xb9,0x1a};
const char pistol15name[] = "Pistol Tactical +SUPPRESSOR +STEADY AIM +SKIN01";
const GUID pistol16guid = {0x86c6fbee,0x4410,0x4e0b,0xbb,0x8b,0xdb,0xd6,0x53,0x69,0x46,0x8f};
const char pistol16name[] = "Firearms Hero Pistol Tactical Silenced Base";
const GUID pistol17guid = {0x9cb5c5dd,0x0ea9,0x454f,0x98,0xfc,0xed,0xaa,0xe7,0xa9,0x1d,0x68};
const char pistol17name[] = "Pistol Light +EXTENDED MAG +AMMO +BULLET DANCER +SKIN01";
const GUID pistol18guid = {0x9e896f52,0x6339,0x42d4,0x9c,0x27,0x93,0x1b,0xe5,0x26,0xbf,0xa7};
const char pistol18name[] = "Firearms Hero Pistol Tactical Base";
const GUID pistol19guid = {0xa59dff0c,0x031a,0x45dd,0x86,0xef,0x72,0xbb,0xb8,0x9c,0xf0,0xf4};
const char pistol19name[] = "Pistol Light +EXTENDED MAG +AMMO +SKIN01";
const GUID pistol20guid = {0xbbd802e2,0x7b21,0x46d8,0x8f,0x59,0x9d,0xbb,0x45,0x2f,0xf9,0x95};
const char pistol20name[] = "Firearms Hero Pistol Magnum Base";
const GUID pistol21guid = {0xbe4e7b4e,0xd895,0x47c1,0x97,0x9d,0xd7,0x9b,0xfb,0xe7,0x9a,0x02};
const char pistol21name[] = "Pistol Tactical +FULLAUTO +SKIN01";
const GUID pistol22guid = {0xc40cf69b,0x6069,0x49a5,0x96,0x58,0xfb,0x2c,0x62,0x06,0xd5,0x25};
const char pistol22name[] = "Pistol Tactical +STEADY AIM +SKIN01";
const GUID pistol23guid = {0xc8a09c31,0xa53e,0x436f,0x84,0x21,0xa4,0xdc,0x41,0x15,0xf6,0x33};
const char pistol23name[] = "Krugermeier 2-2  +SUPPRESSOR +SKIN08";
const GUID pistol24guid = {0xcf2d4606,0x7d04,0x4fa7,0x8e,0x4a,0xf4,0x80,0x38,0x61,0xf5,0xf7};
const char pistol24name[] = "Pistol Light +DAMAGE +SKIN01";
const GUID pistol25guid = {0xd68e927b,0x5786,0x45c4,0xa4,0xfc,0xc6,0xe7,0xf9,0xf4,0x6f,0xb5};
const char pistol25name[] = "Pistol Light +SUPPRESSOR +EXTENDED MAG +SKIN04";
const GUID pistol26guid = {0xe55c71d6,0xcbf6,0x41b8,0x88,0x38,0x2d,0x1b,0xe1,0xd0,0x7e,0x1c};
const char pistol26name[] = "Caseless Custom 5mm - nofrisk derived from Tactical Pistol";
const GUID pistol27guid = {0xe70adb5b,0x0646,0x4f88,0xbd,0x4a,0x85,0xbe,0xa7,0xa2,0xa6,0x54};
const char pistol27name[] = "Pistol Tactical +SUPPRESSOR + STEADY AIM +SKIN02";
const GUID pistol28guid = {0xf09db71f,0x94d7,0x4f97,0xb1,0x54,0xe1,0xc9,0x37,0x34,0x72,0xe7};
const char pistol28name[] = "Pistol Tactical +SKIN01";
const GUID pistol29guid = {0xf196798d,0xf4a4,0x4808,0x9c,0x9c,0x01,0x9f,0x92,0x17,0xc6,0x5a};
const char pistol29name[] = "Pistol Tactical +KNOCKDOWN +SKIN01";
const GUID pistol30guid = {0xf271ed8f,0x4af2,0x483b,0x9c,0x21,0x45,0xfd,0x74,0x7d,0x9a,0xd6};
const char pistol30name[] = "Pistol Tactical +DAMAGE +SKIN01";
const GUID pistol31guid = {0xf91cf558,0x04a5,0x4fd8,0x88,0x14,0xb1,0xc7,0x65,0x66,0x8b,0x39};
const char pistol31name[] = "Pistol Light +SUPPRESSOR +EXTENDED MAG +SKIN03";
const GUID pistol32guid = {0xfbed5e11,0x08fb,0x4bba,0xaa,0x3d,0xac,0x64,0x35,0x41,0xe3,0x8a};
const char pistol32name[] = "Firearms Hero Pistol Light Base";
const GUID pistol33guid = {0xfd309ddf,0x76ae,0x4186,0x89,0xdc,0x18,0x02,0x9e,0x63,0xd6,0x86};
const char pistol33name[] = "Pistol Tactical +STABLE +SUPPRESSOR +SKIN01";
const GUID pistol34guid = {0x6707e470,0x0f7e,0x49f5,0x90,0xf2,0x4e,0x01,0x48,0x65,0x77,0xc3};
const char pistol34name[] = "Firearms Hero No-frisk Pistol";
const char pistol[] = "pistol";
#define pistolARRLEN 35
guid_name_struct pistol_guid_name[pistolARRLEN] = {
	(const GUID* const)&pistol0guid, (const char* const)&pistol0name,
	(const GUID* const)&pistol1guid, (const char* const)&pistol1name,
	(const GUID* const)&pistol2guid, (const char* const)&pistol2name,
	(const GUID* const)&pistol3guid, (const char* const)&pistol3name,
	(const GUID* const)&pistol4guid, (const char* const)&pistol4name,
	(const GUID* const)&pistol5guid, (const char* const)&pistol5name,
	(const GUID* const)&pistol6guid, (const char* const)&pistol6name,
	(const GUID* const)&pistol7guid, (const char* const)&pistol7name,
	(const GUID* const)&pistol8guid, (const char* const)&pistol8name,
	(const GUID* const)&pistol9guid, (const char* const)&pistol9name,
	(const GUID* const)&pistol10guid, (const char* const)&pistol10name,
	(const GUID* const)&pistol11guid, (const char* const)&pistol11name,
	(const GUID* const)&pistol12guid, (const char* const)&pistol12name,
	(const GUID* const)&pistol13guid, (const char* const)&pistol13name,
	(const GUID* const)&pistol14guid, (const char* const)&pistol14name,
	(const GUID* const)&pistol15guid, (const char* const)&pistol15name,
	(const GUID* const)&pistol16guid, (const char* const)&pistol16name,
	(const GUID* const)&pistol17guid, (const char* const)&pistol17name,
	(const GUID* const)&pistol18guid, (const char* const)&pistol18name,
	(const GUID* const)&pistol19guid, (const char* const)&pistol19name,
	(const GUID* const)&pistol20guid, (const char* const)&pistol20name,
	(const GUID* const)&pistol21guid, (const char* const)&pistol21name,
	(const GUID* const)&pistol22guid, (const char* const)&pistol22name,
	(const GUID* const)&pistol23guid, (const char* const)&pistol23name,
	(const GUID* const)&pistol24guid, (const char* const)&pistol24name,
	(const GUID* const)&pistol25guid, (const char* const)&pistol25name,
	(const GUID* const)&pistol26guid, (const char* const)&pistol26name,
	(const GUID* const)&pistol27guid, (const char* const)&pistol27name,
	(const GUID* const)&pistol28guid, (const char* const)&pistol28name,
	(const GUID* const)&pistol29guid, (const char* const)&pistol29name,
	(const GUID* const)&pistol30guid, (const char* const)&pistol30name,
	(const GUID* const)&pistol31guid, (const char* const)&pistol31name,
	(const GUID* const)&pistol32guid, (const char* const)&pistol32name,
	(const GUID* const)&pistol33guid, (const char* const)&pistol33name,
	(const GUID* const)&pistol34guid, (const char* const)&pistol34name,
};

const GUID tool0guid = {0x01ed6d15,0xe26e,0x4362,0xb1,0xa6,0x36,0x36,0x84,0xa7,0xd0,0xfd};
const char tool0name[] = "Tool_Crowbar";
const GUID tool1guid = {0x12cb6b51,0xa6dd,0x4bf5,0x96,0x53,0x0a,0xb7,0x27,0x82,0x0c,0xac};
const char tool1name[] = "Tool_Screwdriver";
const GUID tool2guid = {0x5ffda47b,0xf445,0x44c7,0x88,0x12,0x8d,0x7e,0x39,0xe4,0x92,0x8c};
const char tool2name[] = "Tool_Crowbar_Holiday_Present";
const GUID tool3guid = {0x6adddf7e,0x6879,0x4d51,0xa7,0xe2,0x6a,0x25,0xff,0xdc,0xa6,0xae};
const char tool3name[] = "Tool_Wrench";
const GUID tool4guid = {0xb39d7a0d,0xe839,0x417b,0x88,0x0c,0xcf,0x9b,0x16,0x5d,0x4e,0x11};
const char tool4name[] = "Tool_Lockpick";
const GUID tool5guid = {0xb970a355,0x4296,0x4acc,0x9e,0xc9,0x58,0x4e,0x69,0xa7,0x9e,0xed};
const char tool5name[] = "Tool_Keycard Hacker";
const char tool[] = "tool";
#define toolARRLEN 6
guid_name_struct tool_guid_name[toolARRLEN] = {
	(const GUID* const)&tool0guid, (const char* const)&tool0name,
	(const GUID* const)&tool1guid, (const char* const)&tool1name,
	(const GUID* const)&tool2guid, (const char* const)&tool2name,
	(const GUID* const)&tool3guid, (const char* const)&tool3name,
	(const GUID* const)&tool4guid, (const char* const)&tool4name,
	(const GUID* const)&tool5guid, (const char* const)&tool5name,
};

const GUID explosives0guid = {0x0a5bebc8,0x0148,0x4745,0x90,0xb2,0xf5,0x4b,0x3c,0x71,0x11,0x6c};
const char explosives0name[] = "ICA Device Napoleon Figure Remote Explosive";
const GUID explosives1guid = {0x356b016c,0xfdb3,0x47d3,0x91,0x3c,0x39,0x73,0xe6,0xa5,0xa8,0xcf};
const char explosives1name[] = "ICA Device RubberDuck Remote Explosive";
const GUID explosives2guid = {0x3dd70135,0x55c0,0x4199,0xb5,0x5b,0xd8,0x0e,0xa1,0xac,0x07,0x0b};
const char explosives2name[] = "ICA Device Modular Proximity Explosive";
const GUID explosives3guid = {0x3fc1a8f8,0xf8fc,0x422e,0x88,0x4a,0x73,0x0c,0xa9,0x49,0x17,0x37};
const char explosives3name[] = "Action figure proximity explosive";
const GUID explosives4guid = {0x4ca96340,0xae60,0x427b,0xa0,0x11,0x9e,0x29,0x6c,0xd6,0x7f,0xd9};
const char explosives4name[] = "ICA Device RubberDuck Proximity Explosive";
const GUID explosives5guid = {0x74a22451,0x8920,0x488f,0x88,0x3c,0xb5,0x24,0x6b,0xa0,0xf9,0xf3};
const char explosives5name[] = "ICA Device Explosive Phone";
const GUID explosives6guid = {0x7c691c03,0x7c6b,0x4eb4,0x9a,0x68,0x89,0x8e,0xfe,0x5e,0xed,0xaa};
const char explosives6name[] = "Military Remote Explosive";
const GUID explosives7guid = {0x7d0c107e,0x4279,0x4fda,0xa7,0xe2,0x77,0x35,0x92,0x71,0xcb,0x9a};
const char explosives7name[] = "ICA Device Modular Remote Explosive";
const GUID explosives8guid = {0x9aabe1cf,0x2a11,0x49d5,0x8b,0xaa,0xe8,0xed,0x3e,0xf2,0x2c,0x3e};
const char explosives8name[] = "SONY PREORDER WHITE REMOTE RUBBERDUCK EXPLOSIVE";
const GUID explosives9guid = {0xb20fc045,0xe453,0x4280,0x8b,0x18,0xb0,0xa0,0xe5,0xc1,0x72,0x36};
const char explosives9name[] = "ICA Device C4 Proximity Explosive";
const GUID explosives10guid = {0xc95c55aa,0x34e5,0x42bd,0xbf,0x27,0x32,0xbe,0x39,0x78,0xb2,0x69};
const char explosives10name[] = "Explosive Golf Ball";
const GUID explosives11guid = {0xccdd6689,0x092d,0x49b2,0x85,0xf8,0x41,0x6a,0x02,0xe2,0x55,0x66};
const char explosives11name[] = "ICA Device C4 Remote Explosive";
const GUID explosives12guid = {0xfc715a9a,0x3bf1,0x4768,0xbd,0x67,0x0d,0xef,0x61,0xb9,0x25,0x51};
const char explosives12name[] = "ICA Device Modular Breach Charge";
const char explosives[] = "explosives";
#define explosivesARRLEN 13
guid_name_struct explosives_guid_name[explosivesARRLEN] = {
	(const GUID* const)&explosives0guid, (const char* const)&explosives0name,
	(const GUID* const)&explosives1guid, (const char* const)&explosives1name,
	(const GUID* const)&explosives2guid, (const char* const)&explosives2name,
	(const GUID* const)&explosives3guid, (const char* const)&explosives3name,
	(const GUID* const)&explosives4guid, (const char* const)&explosives4name,
	(const GUID* const)&explosives5guid, (const char* const)&explosives5name,
	(const GUID* const)&explosives6guid, (const char* const)&explosives6name,
	(const GUID* const)&explosives7guid, (const char* const)&explosives7name,
	(const GUID* const)&explosives8guid, (const char* const)&explosives8name,
	(const GUID* const)&explosives9guid, (const char* const)&explosives9name,
	(const GUID* const)&explosives10guid, (const char* const)&explosives10name,
	(const GUID* const)&explosives11guid, (const char* const)&explosives11name,
	(const GUID* const)&explosives12guid, (const char* const)&explosives12name,
};

const GUID sniperrifle0guid = {0x034ce4ab,0xb85a,0x4706,0xbd,0xef,0xcb,0xa7,0x7f,0x9b,0x45,0xf7};
const char sniperrifle0name[] = "Sniper Heavy +SUPPRESSOR +SUBSONIC +SCOUTING SCOPE +SKIN09 Tiger Camo";
const GUID sniperrifle1guid = {0x1264f20b,0xb901,0x4d36,0xbc,0x03,0xa9,0x11,0x57,0x09,0xb5,0x31};
const char sniperrifle1name[] = "Sniper Heavy +PIERCING +SKIN01";
const GUID sniperrifle2guid = {0x13b8fc51,0xfbc8,0x4206,0xbf,0x0a,0x82,0x00,0xa8,0x81,0x75,0xa4};
const char sniperrifle2name[] = "Sniper Heavy +RATE OF FIRE +SKIN01";
const GUID sniperrifle3guid = {0x1907eda1,0x5b51,0x490f,0xa7,0xb8,0x1a,0xe0,0x90,0xbc,0x00,0xae};
const char sniperrifle3name[] = "Sniper Heavy +LESS BOBBING +EXTENDED MAG +LESS DRAG +STABLE +SKIN01";
const GUID sniperrifle4guid = {0x1bbdae30,0xdb26,0x462a,0xbe,0xda,0xff,0x5f,0x51,0xb9,0x55,0xb9};
const char sniperrifle4name[] = "Sniper Heavy +SUPPRESSOR +SUBSONIC +SCOUTING SCOPE +SKIN04";
const GUID sniperrifle5guid = {0x1e100516,0x2f0a,0x41e3,0x80,0xa1,0x4a,0x1e,0x43,0x18,0x0b,0x86};
const char sniperrifle5name[] = "Sniper Heavy +HAILSTORM +SKIN01";
const GUID sniperrifle6guid = {0x2bb2fe71,0x370d,0x4af9,0xa9,0x41,0x0e,0xd3,0xff,0x70,0xf5,0xbb};
const char sniperrifle6name[] = "Firearms Hero Sniper Heavy Base";
const GUID sniperrifle7guid = {0x370580fc,0x7fcf,0x47f8,0xb9,0x94,0xce,0xbd,0x27,0x9f,0x69,0xf9};
const char sniperrifle7name[] = "Sniper Heavy +SUPPRESSOR +SUBSONIC +SCOUTING SCOPE +SKIN01";
const GUID sniperrifle8guid = {0x42c446d9,0x022e,0x4c0e,0x92,0x1f,0xed,0x1e,0x72,0x6c,0x9f,0x15};
const char sniperrifle8name[] = "Sniper Heavy +SUPPRESSOR +SUBSONIC +SCOUTING SCOPE +MARKSMAN +SKIN03";
const GUID sniperrifle9guid = {0x50434d64,0x7fdc,0x4791,0xb0,0x87,0xf6,0x2d,0xf3,0x21,0x14,0x1e};
const char sniperrifle9name[] = "Sniper Heavy +MARKSMAN +SKIN01";
const GUID sniperrifle10guid = {0x52d2ebd9,0xf0f7,0x4659,0xbe,0x35,0xbe,0x7b,0x41,0x21,0x34,0x6c};
const char sniperrifle10name[] = "Sniper Heavy +ADDED ZOOM +SUPPRESSOR +SKIN01";
const GUID sniperrifle11guid = {0x54bba84c,0x6751,0x430e,0xb4,0x7d,0xe4,0xb5,0xdd,0xf7,0xa8,0x35};
const char sniperrifle11name[] = "Classic Sniper W2000 aka Sieger 300 - Sniper Medium Base";
const GUID sniperrifle12guid = {0x82642e14,0xc6d7,0x43b3,0x8b,0x9c,0x39,0x68,0x23,0xa2,0x85,0x9a};
const char sniperrifle12name[] = "Firearms Hero Sniper Medium Base (Classic)";
const GUID sniperrifle13guid = {0x8f4cd8c1,0x6ee6,0x4686,0x8a,0x0e,0x52,0xa8,0x23,0xee,0xc1,0x65};
const char sniperrifle13name[] = "Firearms Hero Sniper Heavy Base TEST";
const GUID sniperrifle14guid = {0x907e0277,0x7806,0x42a4,0xb4,0xb2,0x33,0x8c,0xf8,0xdd,0x93,0x91};
const char sniperrifle14name[] = "Sieger 300 Advanced - Medium Sniper Classic Ave Maria Sound";
const GUID sniperrifle15guid = {0x92d5d66e,0x3d84,0x4fcb,0x97,0xd2,0xff,0x60,0xfb,0x46,0x65,0x04};
const char sniperrifle15name[] = "Sniper Heavy +LESS BOBBING +SUPPRESSOR + ADDED ZOOM +SKIN01";
const GUID sniperrifle16guid = {0xc0f72c92,0xf514,0x40b7,0xa3,0x5c,0x2f,0x57,0x09,0xb9,0x9f,0xce};
const char sniperrifle16name[] = "Firearms Hero Sniper Heavy Scout Base (Scout)";
const GUID sniperrifle17guid = {0xd588f7b9,0x0ae3,0x4599,0xa9,0x3b,0x48,0x72,0x38,0x0f,0x7f,0x40};
const char sniperrifle17name[] = "Sniper Heavy +SKIN01";
const GUID sniperrifle18guid = {0xeedb7f84,0x896d,0x403b,0x90,0x5b,0x11,0xb1,0x05,0xe7,0xce,0x35};
const char sniperrifle18name[] = "Sniper Heavy +SUPPRESSOR +SUBSONIC +SCOUTING SCOPE +SKIN03";
const GUID sniperrifle19guid = {0xf301f605,0x007c,0x4fe1,0xaa,0x99,0xa8,0xcd,0x2c,0xae,0x03,0x3f};
const char sniperrifle19name[] = "Sieger 300 Ghost _ GOTY Medium Sniper (Dark Sniper)";
const GUID sniperrifle20guid = {0xf873158f,0x1357,0x479c,0xa0,0x19,0x05,0x07,0x35,0xd4,0x02,0xb8};
const char sniperrifle20name[] = "Sniper Heavy +AMMO +SKIN01";
const GUID sniperrifle21guid = {0xd7200af3,0x571f,0x44b5,0xab,0x8e,0x61,0x6b,0xc0,0xe6,0xdd,0xc8};
const char sniperrifle21name[] = "Firearms Hero Sniper Heavy Base Ave Maria";
const char sniperrifle[] = "sniperrifle";
#define sniperrifleARRLEN 22
guid_name_struct sniperrifle_guid_name[sniperrifleARRLEN] = {
	(const GUID* const)&sniperrifle0guid, (const char* const)&sniperrifle0name,
	(const GUID* const)&sniperrifle1guid, (const char* const)&sniperrifle1name,
	(const GUID* const)&sniperrifle2guid, (const char* const)&sniperrifle2name,
	(const GUID* const)&sniperrifle3guid, (const char* const)&sniperrifle3name,
	(const GUID* const)&sniperrifle4guid, (const char* const)&sniperrifle4name,
	(const GUID* const)&sniperrifle5guid, (const char* const)&sniperrifle5name,
	(const GUID* const)&sniperrifle6guid, (const char* const)&sniperrifle6name,
	(const GUID* const)&sniperrifle7guid, (const char* const)&sniperrifle7name,
	(const GUID* const)&sniperrifle8guid, (const char* const)&sniperrifle8name,
	(const GUID* const)&sniperrifle9guid, (const char* const)&sniperrifle9name,
	(const GUID* const)&sniperrifle10guid, (const char* const)&sniperrifle10name,
	(const GUID* const)&sniperrifle11guid, (const char* const)&sniperrifle11name,
	(const GUID* const)&sniperrifle12guid, (const char* const)&sniperrifle12name,
	(const GUID* const)&sniperrifle13guid, (const char* const)&sniperrifle13name,
	(const GUID* const)&sniperrifle14guid, (const char* const)&sniperrifle14name,
	(const GUID* const)&sniperrifle15guid, (const char* const)&sniperrifle15name,
	(const GUID* const)&sniperrifle16guid, (const char* const)&sniperrifle16name,
	(const GUID* const)&sniperrifle17guid, (const char* const)&sniperrifle17name,
	(const GUID* const)&sniperrifle18guid, (const char* const)&sniperrifle18name,
	(const GUID* const)&sniperrifle19guid, (const char* const)&sniperrifle19name,
	(const GUID* const)&sniperrifle20guid, (const char* const)&sniperrifle20name,
	(const GUID* const)&sniperrifle21guid, (const char* const)&sniperrifle21name,
};

const GUID assaultrifle0guid = {0x03658b5a,0xb49e,0x4e82,0x82,0xe2,0xf5,0xd8,0xc5,0xcc,0x60,0x2e};
const char assaultrifle0name[] = "Rifle SemiAuto +SUPPRESSOR +SKIN10 Jungle Camo";
const GUID assaultrifle1guid = {0x0a1d5a9b,0xcc9a,0x46cd,0x8c,0xf4,0x63,0x45,0xbe,0x4d,0xe2,0x9b};
const char assaultrifle1name[] = "Rifle FullAuto +STABLE +SUPPRESSOR +SKIN01";
const GUID assaultrifle2guid = {0x16edb112,0x58cc,0x4069,0xa7,0xdd,0xeb,0xd2,0x58,0xb1,0x40,0x44};
const char assaultrifle2name[] = "AssaultRifle02 NPC";
const GUID assaultrifle3guid = {0x2adbeb2b,0x23f5,0x46ff,0x8d,0xd3,0x90,0xf8,0xa5,0xb7,0xa0,0xff};
const char assaultrifle3name[] = "Rifle FullAuto +SUPPRESSOR +POINTSHOOTING +ONE MAN ARMY +SKIN01";
const GUID assaultrifle4guid = {0x2f6eec38,0x45ea,0x49df,0x83,0xa2,0x0b,0x98,0xa8,0x58,0xe6,0x0a};
const char assaultrifle4name[] = "RS-15 AssaultRifle Heavy +SUPPRESSOR + SKIN08";
const GUID assaultrifle5guid = {0x334645bf,0xb37b,0x4310,0x92,0x5c,0x76,0x7c,0x3b,0xf7,0x06,0xb3};
const char assaultrifle5name[] = "Rifle SemiAuto +SUPPRESSOR +SKIN01";
const GUID assaultrifle6guid = {0x347b884d,0xf95d,0x4953,0xa6,0x5c,0x40,0x81,0xfb,0xfc,0xe8,0x8d};
const char assaultrifle6name[] = "Firearms Hero AssaultRifle FullAuto Heavy Base";
const GUID assaultrifle7guid = {0x3645986a,0x558c,0x4902,0xae,0x4f,0x31,0xc7,0x65,0x8b,0xa5,0x08};
const char assaultrifle7name[] = "Rifle FullAuto +EXTENDED MAG +SKIN04";
const GUID assaultrifle8guid = {0x39b346c5,0xd32a,0x4bb3,0xbf,0xe7,0xcb,0x3d,0x64,0x8d,0x01,0x71};
const char assaultrifle8name[] = "Rifle FullAuto +HAILSTORM +SKIN01";
const GUID assaultrifle9guid = {0x50c91e0d,0x2780,0x4fd1,0xad,0xe6,0x65,0xd7,0x3f,0xf5,0xc0,0x0d};
const char assaultrifle9name[] = "Firearms Hero Rifle SemiAuto Base";
const GUID assaultrifle10guid = {0x584e026c,0xf2b9,0x4c54,0xa5,0x28,0x19,0x49,0x2c,0x75,0x38,0xd9};
const char assaultrifle10name[] = "Rifle SemiAuto +SKIN01";
const GUID assaultrifle11guid = {0x6b93848c,0x8f1d,0x42eb,0x81,0x6f,0xba,0xb6,0x1b,0x56,0xd8,0xa5};
const char assaultrifle11name[] = "AssaultRifle03 NPC Shooting Range version";
const GUID assaultrifle12guid = {0x6dda9c11,0xd472,0x4ae9,0xaa,0xdc,0xb9,0x16,0x88,0x15,0x83,0xa7};
const char assaultrifle12name[] = "Rifle FullAuto +SUPPRESSOR +SKIN06";
const GUID assaultrifle13guid = {0x7268a96e,0x87bb,0x4a12,0xa0,0x3c,0xed,0x4f,0x58,0xb5,0xd4,0x12};
const char assaultrifle13name[] = "Rifle FullAuto +PIERCING +ONE MAN ARMY +SKIN06";
const GUID assaultrifle14guid = {0x7373fafa,0x7adb,0x4c14,0xac,0x02,0x22,0x58,0x95,0xf9,0xeb,0x7f};
const char assaultrifle14name[] = "Rifle FullAuto +SUPPRESSOR +SKIN07 Dark Black";
const GUID assaultrifle15guid = {0x73b012eb,0xcf5f,0x4096,0x86,0xaf,0xe3,0xcc,0x66,0xe5,0x5e,0xf6};
const char assaultrifle15name[] = "Rifle SemiAuto +STABLE +SUPPRESSOR +STEADY AIM +SKIN01";
const GUID assaultrifle16guid = {0x76a3920f,0xf307,0x48a8,0xae,0x2b,0x7d,0x0a,0x6c,0x50,0x99,0xb5};
const char assaultrifle16name[] = "Rifle SemiAuto +HAILSTORM +SKIN01";
const GUID assaultrifle17guid = {0x77e20086,0x6d8a,0x4d85,0x9d,0xc1,0xb2,0xc2,0x75,0xb4,0xca,0xb4};
const char assaultrifle17name[] = "Rifle FullAuto +RATE OF FIRE +DAMAGE +SKIN01";
const GUID assaultrifle18guid = {0x7e1b2364,0xa190,0x41f7,0xa1,0x6d,0xa7,0xd7,0xa9,0xa2,0xf6,0x23};
const char assaultrifle18name[] = "Rifle SemiAuto +SUPPRESSOR +STABLE +STEADY AIM +SKIN07";
const GUID assaultrifle19guid = {0x87351783,0xbce0,0x4a76,0x8e,0x4d,0xca,0xab,0x36,0x8f,0x7d,0x1b};
const char assaultrifle19name[] = "Rifle FullAuto +RATE OF FIRE +SKIN01";
const GUID assaultrifle20guid = {0x89879b09,0xf093,0x4f71,0xbc,0x37,0x6e,0x4d,0x1d,0x31,0x86,0xa1};
const char assaultrifle20name[] = "Rifle FullAuto +SUPPRESSOR +SKIN01";
const GUID assaultrifle21guid = {0x8997c964,0x5ed9,0x4348,0x8b,0xe3,0x8a,0xb2,0x79,0x1c,0xd5,0xdb};
const char assaultrifle21name[] = "Rifle SemiAuto +DAMAGE +SKIN01";
const GUID assaultrifle22guid = {0x912ff05f,0xfe52,0x48fd,0x89,0x28,0xc4,0xeb,0x8d,0x42,0xea,0xe1};
const char assaultrifle22name[] = "Rifle SemiAuto +STABLE +SKIN01";
const GUID assaultrifle23guid = {0x916e965c,0x883d,0x4f5a,0xab,0xbd,0x7d,0xc2,0x65,0x3c,0xa1,0x0c};
const char assaultrifle23name[] = "Rifle FullAuto +DAMAGE +SKIN01";
const GUID assaultrifle24guid = {0x93c7e5f2,0x6b92,0x4487,0xaf,0x09,0x13,0x68,0x5e,0xd7,0x78,0x99};
const char assaultrifle24name[] = "Firearms Hero AssaultRifle FullAuto Base";
const GUID assaultrifle25guid = {0xa15af673,0x8e21,0x47e3,0xbd,0xfa,0xf5,0xde,0xa7,0xb5,0xf9,0xe9};
const char assaultrifle25name[] = "Rifle FullAuto +SKIN01";
const GUID assaultrifle26guid = {0xa7d04ba5,0x6c22,0x4c8e,0xbf,0xef,0x8c,0xb8,0xd8,0xdf,0x53,0xf1};
const char assaultrifle26name[] = "Rifle SemiAuto +AMMO +PIERCING +SKIN01";
const GUID assaultrifle27guid = {0xc7887ee8,0x5022,0x45fa,0xa6,0x8c,0x14,0xc0,0x6f,0xa8,0x7a,0x9e};
const char assaultrifle27name[] = "Rifle FullAuto +AMMO +EXTENDED MAG +SKIN01";
const GUID assaultrifle28guid = {0xd365f5f5,0x1f5e,0x406d,0xa3,0x5e,0xc3,0x42,0x12,0xce,0x97,0xa0};
const char assaultrifle28name[] = "Rifle SemiAuto +DAMAGE +KNOCKDOWN +BULLETDANCER +SKIN01";
const GUID assaultrifle29guid = {0xd8aa6eba,0x0cb7,0x4ed4,0xab,0x99,0x97,0x5f,0x27,0x93,0xd7,0x31};
const char assaultrifle29name[] = "AssaultRifle01 NPC";
const GUID assaultrifle30guid = {0xec24b907,0x5fbf,0x4996,0x91,0xa1,0x59,0xc1,0x0f,0xad,0x67,0x79};
const char assaultrifle30name[] = "Rifle FullAuto +SKIN03";
const GUID assaultrifle31guid = {0xed4e2462,0x5c7d,0x4e4e,0xa1,0xca,0xef,0xbb,0xa5,0xd9,0x4c,0x98};
const char assaultrifle31name[] = "Rifle FullAuto +RATE OF FIRE +KNOCKDOWN +BULLET DANCER +SKIN01";
const GUID assaultrifle32guid = {0xf00998b0,0x981e,0x4f0a,0x82,0xd8,0x2c,0x62,0x06,0xfd,0x48,0x25};
const char assaultrifle32name[] = "Rifle SemiAuto +RATE OF FIRE +SKIN01";
const GUID assaultrifle33guid = {0xf8094bb5,0x6e2a,0x42d8,0xaa,0x82,0x88,0xeb,0xb7,0x74,0x4c,0x3f};
const char assaultrifle33name[] = "Rifle SemiAuto +EXTENDED MAG +SUPPRESSOR +SKIN01";
const char assaultrifle[] = "assaultrifle";
#define assaultrifleARRLEN 34
guid_name_struct assaultrifle_guid_name[assaultrifleARRLEN] = {
	(const GUID* const)&assaultrifle0guid, (const char* const)&assaultrifle0name,
	(const GUID* const)&assaultrifle1guid, (const char* const)&assaultrifle1name,
	(const GUID* const)&assaultrifle2guid, (const char* const)&assaultrifle2name,
	(const GUID* const)&assaultrifle3guid, (const char* const)&assaultrifle3name,
	(const GUID* const)&assaultrifle4guid, (const char* const)&assaultrifle4name,
	(const GUID* const)&assaultrifle5guid, (const char* const)&assaultrifle5name,
	(const GUID* const)&assaultrifle6guid, (const char* const)&assaultrifle6name,
	(const GUID* const)&assaultrifle7guid, (const char* const)&assaultrifle7name,
	(const GUID* const)&assaultrifle8guid, (const char* const)&assaultrifle8name,
	(const GUID* const)&assaultrifle9guid, (const char* const)&assaultrifle9name,
	(const GUID* const)&assaultrifle10guid, (const char* const)&assaultrifle10name,
	(const GUID* const)&assaultrifle11guid, (const char* const)&assaultrifle11name,
	(const GUID* const)&assaultrifle12guid, (const char* const)&assaultrifle12name,
	(const GUID* const)&assaultrifle13guid, (const char* const)&assaultrifle13name,
	(const GUID* const)&assaultrifle14guid, (const char* const)&assaultrifle14name,
	(const GUID* const)&assaultrifle15guid, (const char* const)&assaultrifle15name,
	(const GUID* const)&assaultrifle16guid, (const char* const)&assaultrifle16name,
	(const GUID* const)&assaultrifle17guid, (const char* const)&assaultrifle17name,
	(const GUID* const)&assaultrifle18guid, (const char* const)&assaultrifle18name,
	(const GUID* const)&assaultrifle19guid, (const char* const)&assaultrifle19name,
	(const GUID* const)&assaultrifle20guid, (const char* const)&assaultrifle20name,
	(const GUID* const)&assaultrifle21guid, (const char* const)&assaultrifle21name,
	(const GUID* const)&assaultrifle22guid, (const char* const)&assaultrifle22name,
	(const GUID* const)&assaultrifle23guid, (const char* const)&assaultrifle23name,
	(const GUID* const)&assaultrifle24guid, (const char* const)&assaultrifle24name,
	(const GUID* const)&assaultrifle25guid, (const char* const)&assaultrifle25name,
	(const GUID* const)&assaultrifle26guid, (const char* const)&assaultrifle26name,
	(const GUID* const)&assaultrifle27guid, (const char* const)&assaultrifle27name,
	(const GUID* const)&assaultrifle28guid, (const char* const)&assaultrifle28name,
	(const GUID* const)&assaultrifle29guid, (const char* const)&assaultrifle29name,
	(const GUID* const)&assaultrifle30guid, (const char* const)&assaultrifle30name,
	(const GUID* const)&assaultrifle31guid, (const char* const)&assaultrifle31name,
	(const GUID* const)&assaultrifle32guid, (const char* const)&assaultrifle32name,
	(const GUID* const)&assaultrifle33guid, (const char* const)&assaultrifle33name,
};

const GUID shotgun0guid = {0x2160c773,0x61d7,0x4bce,0xb7,0xf6,0x24,0xb5,0xc2,0x5a,0xfb,0xb5};
const char shotgun0name[] = "Shotgun SemiAuto +EXTENDED MAG +POINTSHOOTING +CROWDCONTROL +SKIN01";
const GUID shotgun1guid = {0x34dff939,0x6805,0x4d79,0xad,0xc2,0x5b,0xb4,0xe3,0x7e,0x10,0x9a};
const char shotgun1name[] = "Shotgun SemiAuto +HAILSTORM +SKIN01";
const GUID shotgun2guid = {0x35182a4f,0x9707,0x42ac,0xb4,0x49,0x77,0xfc,0xe3,0xf5,0xf6,0x77};
const char shotgun2name[] = "Firearms Hero Shotgun Heavy Base";
const GUID shotgun3guid = {0x545ff36e,0xb43c,0x4a35,0x9a,0xb3,0x68,0x0b,0x23,0xb9,0xe3,0x54};
const char shotgun3name[] = "Shotgun SemiAuto +SUPPRESSOR +SKIN01";
const GUID shotgun4guid = {0x6f5afd22,0x33f0,0x40f0,0x85,0x87,0xfa,0x15,0x88,0xf3,0xd6,0x9c};
const char shotgun4name[] = "Shotgun SemiAuto +POINTSHOOTING +SKIN01";
const GUID shotgun5guid = {0x784784a1,0x6e50,0x46aa,0xbe,0xff,0xa4,0x60,0xe0,0x03,0xee,0x99};
const char shotgun5name[] = "Shotgun SemiAuto +POINTSHOOTING +SKIN03";
const GUID shotgun6guid = {0x7a86ce95,0xaa89,0x4204,0x9b,0xf1,0x52,0xea,0xa9,0xa5,0x03,0xa9};
const char shotgun6name[] = "Derived NPC Shotgun02 Bartoli .12g ";
const GUID shotgun7guid = {0x7f31d897,0xa62f,0x448c,0xbe,0x0d,0x79,0xd5,0x65,0xe2,0xfa,0xa7};
const char shotgun7name[] = "Shotgun02 NPC Bartoli 12G";
const GUID shotgun8guid = {0x881979b0,0xc506,0x41a5,0xbc,0x7a,0xa6,0x3b,0xa4,0xc8,0x12,0xad};
const char shotgun8name[] = "Firearms Hero Shotgun Standard Base";
const GUID shotgun9guid = {0x8a2acadb,0x1669,0x4f29,0x9e,0x2b,0xfa,0xde,0x79,0xc5,0x82,0x6f};
const char shotgun9name[] = "Shotgun Standard +SKIN01";
const GUID shotgun10guid = {0x901a3b51,0x51a0,0x4236,0xbd,0xf2,0x23,0xd2,0x06,0x96,0xb3,0x58};
const char shotgun10name[] = "Shotgun01 NPC Tactical Bartoli 12G";
const GUID shotgun11guid = {0xa1afaa63,0xdd9b,0x4209,0xab,0xf3,0x33,0x5e,0x19,0xaf,0x37,0x78};
const char shotgun11name[] = "Shotgun SemiAuto +AMMO +SKIN01";
const GUID shotgun12guid = {0xac3905d9,0x25b1,0x4bab,0xa0,0x5f,0xc0,0x88,0x83,0x10,0x7c,0x98};
const char shotgun12name[] = "Shotgun SemiAuto +EXTENDED MAG +SKIN01";
const GUID shotgun13guid = {0xbca1d600,0x49e5,0x4c90,0x90,0x33,0x4d,0xb1,0x37,0x00,0x58,0x18};
const char shotgun13name[] = "Shotgun SemiAuto +KNOCKDOWN +SKIN01";
const GUID shotgun14guid = {0xc46c9e45,0x26ed,0x469c,0xb7,0xb4,0xc8,0xbc,0xc1,0x41,0x05,0x27};
const char shotgun14name[] = "Shotgun SemiAuto +FULLAUTO +SKIN01";
const GUID shotgun15guid = {0xd075aa8e,0xf334,0x4fa1,0x88,0x0f,0x52,0x5b,0x0e,0x53,0x1e,0xc6};
const char shotgun15name[] = "Shotgun SemiAuto +DAMAGE +SKIN01";
const GUID shotgun16guid = {0xd5728a0f,0xfe8d,0x4e2d,0x93,0x50,0x03,0xcf,0x42,0x43,0xc9,0x8e};
const char shotgun16name[] = "Shotgun SemiAuto +SKIN01";
const GUID shotgun17guid = {0xd9e92556,0x50fa,0x4e4d,0x94,0x03,0x52,0x0e,0xca,0x37,0x23,0x88};
const char shotgun17name[] = "Derived NPC Shotgun02 Bartoli .12g +ONE MAN ARMY";
const GUID shotgun18guid = {0xeb9495e1,0x7d68,0x44ef,0x90,0x25,0xa2,0x67,0x70,0x15,0x8b,0x63};
const char shotgun18name[] = "Firearms Hero Exotic Shotgun Room Clearer";
const GUID shotgun19guid = {0xee414800,0x2cbc,0x4271,0xa2,0xbc,0x05,0x00,0x35,0x22,0x93,0x85};
const char shotgun19name[] = "Shotgun Standard +POINTSHOOTING +SKIN01";
const GUID shotgun20guid = {0xf45868b6,0xe4b2,0x4cd3,0xad,0x9c,0xd0,0xa7,0x27,0xb3,0x9d,0xba};
const char shotgun20name[] = "Firearms Hero Shotgun SemiAuto Base";
const GUID shotgun21guid = {0xf6657618,0xd723,0x419f,0xa7,0x1b,0x84,0xd0,0xe9,0x34,0x02,0xe3};
const char shotgun21name[] = "Shotgun SemiAuto +AMMO +RATEOFFIRE +SKIN01";
const char shotgun[] = "shotgun";
#define shotgunARRLEN 22
guid_name_struct shotgun_guid_name[shotgunARRLEN] = {
	(const GUID* const)&shotgun0guid, (const char* const)&shotgun0name,
	(const GUID* const)&shotgun1guid, (const char* const)&shotgun1name,
	(const GUID* const)&shotgun2guid, (const char* const)&shotgun2name,
	(const GUID* const)&shotgun3guid, (const char* const)&shotgun3name,
	(const GUID* const)&shotgun4guid, (const char* const)&shotgun4name,
	(const GUID* const)&shotgun5guid, (const char* const)&shotgun5name,
	(const GUID* const)&shotgun6guid, (const char* const)&shotgun6name,
	(const GUID* const)&shotgun7guid, (const char* const)&shotgun7name,
	(const GUID* const)&shotgun8guid, (const char* const)&shotgun8name,
	(const GUID* const)&shotgun9guid, (const char* const)&shotgun9name,
	(const GUID* const)&shotgun10guid, (const char* const)&shotgun10name,
	(const GUID* const)&shotgun11guid, (const char* const)&shotgun11name,
	(const GUID* const)&shotgun12guid, (const char* const)&shotgun12name,
	(const GUID* const)&shotgun13guid, (const char* const)&shotgun13name,
	(const GUID* const)&shotgun14guid, (const char* const)&shotgun14name,
	(const GUID* const)&shotgun15guid, (const char* const)&shotgun15name,
	(const GUID* const)&shotgun16guid, (const char* const)&shotgun16name,
	(const GUID* const)&shotgun17guid, (const char* const)&shotgun17name,
	(const GUID* const)&shotgun18guid, (const char* const)&shotgun18name,
	(const GUID* const)&shotgun19guid, (const char* const)&shotgun19name,
	(const GUID* const)&shotgun20guid, (const char* const)&shotgun20name,
	(const GUID* const)&shotgun21guid, (const char* const)&shotgun21name,
};

const GUID distraction0guid = {0x196c112b,0x9923,0x4927,0x97,0xcf,0x5d,0x37,0x73,0xae,0x90,0xea};
const char distraction0name[] = "Tool_Gold_Coin";
const GUID distraction1guid = {0x25a4d780,0x3123,0x448d,0xa6,0xe7,0x3d,0xfd,0xbb,0x8c,0x82,0x60};
const char distraction1name[] = "RadioDistraction";
const GUID distraction2guid = {0x2880296a,0x1014,0x4147,0x82,0x8a,0x80,0xd8,0x2d,0x44,0x04,0xfe};
const char distraction2name[] = "ICA Device Modular Music Distraction";
const GUID distraction3guid = {0x661b9cf9,0xe278,0x442a,0xa8,0x7a,0xad,0x87,0xea,0xd5,0x2d,0x7d};
const char distraction3name[] = "ICA Device Modular Audio Distraction";
const GUID distraction4guid = {0x9d7522dd,0x34e3,0x426d,0x94,0x4b,0x20,0xb2,0x2f,0x8c,0xd9,0xdc};
const char distraction4name[] = "Tool_Silver_Coin_Reward";
const GUID distraction5guid = {0xa9758ca5,0xeee1,0x4b0d,0xb3,0x54,0xf8,0xbb,0x12,0x61,0xfa,0xb8};
const char distraction5name[] = "Tool_Copper_Coin_Reward";
const GUID distraction6guid = {0xdda002e9,0x02b1,0x4208,0x82,0xa5,0xcf,0x05,0x9f,0x3c,0x79,0xcf};
const char distraction6name[] = "Tool_Coin";
const GUID distraction7guid = {0xe755471f,0xe6fd,0x438f,0xb3,0x43,0x7c,0x98,0xfb,0xb5,0x01,0x07};
const char distraction7name[] = "Tool_Apricot";
const GUID distraction8guid = {0xe942b814,0xca60,0x4f27,0x97,0x1e,0x9a,0x31,0x41,0xbb,0xdc,0x4d};
const char distraction8name[] = "Tool_Gold_Coin_Reward";
const GUID distraction9guid = {0xec31f55f,0x6109,0x4f97,0x92,0x86,0x8f,0x59,0xfa,0xe6,0x66,0xf6};
const char distraction9name[] = "FireCrackerDistraction";
const char distraction[] = "distraction";
#define distractionARRLEN 10
guid_name_struct distraction_guid_name[distractionARRLEN] = {
	(const GUID* const)&distraction0guid, (const char* const)&distraction0name,
	(const GUID* const)&distraction1guid, (const char* const)&distraction1name,
	(const GUID* const)&distraction2guid, (const char* const)&distraction2name,
	(const GUID* const)&distraction3guid, (const char* const)&distraction3name,
	(const GUID* const)&distraction4guid, (const char* const)&distraction4name,
	(const GUID* const)&distraction5guid, (const char* const)&distraction5name,
	(const GUID* const)&distraction6guid, (const char* const)&distraction6name,
	(const GUID* const)&distraction7guid, (const char* const)&distraction7name,
	(const GUID* const)&distraction8guid, (const char* const)&distraction8name,
	(const GUID* const)&distraction9guid, (const char* const)&distraction9name,
};

const GUID poison0guid = {0x1bfbb69d,0xc876,0x4d05,0xab,0x0b,0xf0,0xbe,0x63,0xb5,0x5b,0x7a};
const char poison0name[] = "Lethal Poison Syringe Antique";
const GUID poison1guid = {0x1c50d6e0,0x11c8,0x4cbc,0xbe,0x05,0xf5,0x1a,0x8e,0x50,0x13,0xbe};
const char poison1name[] = "Emetic Poison Syringe";
const GUID poison2guid = {0x261f1057,0xb1b2,0x4fe0,0xbd,0x0d,0xb6,0x21,0x10,0x29,0x72,0xc8};
const char poison2name[] = "Emetic Poison Syringe Antique";
const GUID poison3guid = {0x262b56ee,0x5a29,0x4853,0xb2,0x28,0x85,0xd1,0x0b,0x71,0xfa,0x15};
const char poison3name[] = "ICA Device Sedative Poisoned Gum";
const GUID poison4guid = {0x7d668011,0x77f9,0x4cae,0x97,0xf1,0xe3,0xed,0xa5,0xe0,0xc8,0xb2};
const char poison4name[] = "Lethal Poison";
const GUID poison5guid = {0x7ff066ff,0x2586,0x4167,0x85,0x6f,0x37,0x15,0x35,0x49,0xbf,0xa9};
const char poison5name[] = "ICA Device Emetic Poisoned Gum";
const GUID poison6guid = {0x88b961c5,0x7235,0x48d1,0x90,0x67,0xe7,0xd3,0x4e,0x75,0xec,0x63};
const char poison6name[] = "Sedative Poison";
const GUID poison7guid = {0x8b37a3a8,0x8a20,0x4262,0x81,0xc5,0x0f,0xcd,0x15,0xf4,0xbb,0xa9};
const char poison7name[] = "Rat Poison";
const GUID poison8guid = {0xa10cf0cb,0x266d,0x498b,0xac,0x29,0x49,0xab,0x10,0xc4,0xe5,0x75};
const char poison8name[] = "Emetic Poison";
const GUID poison9guid = {0xa1f89118,0xd345,0x4367,0x94,0x23,0x62,0x0c,0x3e,0xf5,0xdf,0xba};
const char poison9name[] = "Opportunity Lethal Poison (Pills)";
const GUID poison10guid = {0xaf9ad679,0x6a7c,0x4f8e,0x97,0x00,0xce,0xb5,0xe6,0x88,0x76,0x66};
const char poison10name[] = "Lethal Poison Syringe Modern";
const GUID poison11guid = {0xb386cf6a,0x6a9b,0x4fb5,0xb8,0x79,0x4d,0x55,0x03,0x9d,0x8c,0xed};
const char poison11name[] = "Sedative Syringe Antique";
const GUID poison12guid = {0xc45e59f4,0xd8e1,0x4c37,0xb0,0x79,0x8b,0x74,0xb1,0xfe,0x9b,0x24};
const char poison12name[] = "Sedative Syringe";
const GUID poison13guid = {0xc5ec6168,0x2e5e,0x4340,0xb7,0x1a,0xc6,0x0f,0x2e,0xe6,0xbd,0x66};
const char poison13name[] = "OnlineReward Emetic Pills";
const GUID poison14guid = {0xdfa0c4e9,0x37df,0x4b4e,0x83,0x0b,0x1d,0x4e,0xda,0x61,0x49,0xaf};
const char poison14name[] = "Haemoragic Virus Syringe Modern";
const GUID poison15guid = {0xecf7f361,0xc2aa,0x4d96,0xb6,0x6d,0xe9,0x73,0xc3,0xe8,0x71,0x54};
const char poison15name[] = "OnlineReward Sedative Pills";
const GUID poison16guid = {0xef63eda6,0x6411,0x4ce0,0xb3,0x5b,0x14,0x3f,0xc5,0x76,0x7f,0xc0};
const char poison16name[] = "OnlineReward Lethal Pills";
const GUID poison17guid = {0xf38acb83,0xcb09,0x47d1,0x8e,0xd8,0xdb,0x4d,0x75,0x7c,0x33,0xdd};
const char poison17name[] = "ICA Device Lethal Poisoned Gum";
const char poison[] = "poison";
#define poisonARRLEN 18
guid_name_struct poison_guid_name[poisonARRLEN] = {
	(const GUID* const)&poison0guid, (const char* const)&poison0name,
	(const GUID* const)&poison1guid, (const char* const)&poison1name,
	(const GUID* const)&poison2guid, (const char* const)&poison2name,
	(const GUID* const)&poison3guid, (const char* const)&poison3name,
	(const GUID* const)&poison4guid, (const char* const)&poison4name,
	(const GUID* const)&poison5guid, (const char* const)&poison5name,
	(const GUID* const)&poison6guid, (const char* const)&poison6name,
	(const GUID* const)&poison7guid, (const char* const)&poison7name,
	(const GUID* const)&poison8guid, (const char* const)&poison8name,
	(const GUID* const)&poison9guid, (const char* const)&poison9name,
	(const GUID* const)&poison10guid, (const char* const)&poison10name,
	(const GUID* const)&poison11guid, (const char* const)&poison11name,
	(const GUID* const)&poison12guid, (const char* const)&poison12name,
	(const GUID* const)&poison13guid, (const char* const)&poison13name,
	(const GUID* const)&poison14guid, (const char* const)&poison14name,
	(const GUID* const)&poison15guid, (const char* const)&poison15name,
	(const GUID* const)&poison16guid, (const char* const)&poison16name,
	(const GUID* const)&poison17guid, (const char* const)&poison17name,
};

const GUID smg0guid = {0x055d7b9e,0x1c9c,0x445f,0xb5,0x8c,0xbf,0x9a,0x26,0x84,0xf9,0x8f};
const char smg0name[] = "SMG Tactical +SUPPRESSOR +PIERCING +SKIN01";
const GUID smg1guid = {0x3fd9825d,0x8aa5,0x48e0,0x97,0xa9,0xec,0x8f,0x54,0x1f,0x87,0x1a};
const char smg1name[] = "SMG02 NPC Shaurya";
const GUID smg2guid = {0x4bb0e76e,0x2af8,0x46dc,0x98,0x4f,0x13,0x7c,0x06,0x47,0x72,0x3d};
const char smg2name[] = "SMG Tactical +PIERCING +SKIN01";
const GUID smg3guid = {0x7bf3a6e6,0xb5aa,0x4c88,0xb9,0x53,0xc2,0xc3,0x78,0xd3,0x61,0x18};
const char smg3name[] = "SMG Tactical +RATE OF FIRE +SUPPRESSOR +SKIN01";
const GUID smg4guid = {0x83984d7f,0x3ef1,0x4299,0xb5,0xcd,0xbc,0x7c,0x38,0x04,0xf9,0x89};
const char smg4name[] = "SMG Tactical +STABLE +STEADY AIM +SUPPRESSOR +SKIN01";
const GUID smg5guid = {0xa35c8be4,0x60d1,0x4e83,0xb3,0x06,0x44,0xd5,0x31,0xf8,0xdd,0xb3};
const char smg5name[] = "SMG Tactical +EXTENDED MAG +POINTSHOOTING +SKIN01";
const GUID smg6guid = {0xa6cf1d84,0x0b9b,0x49f6,0xab,0x05,0xe6,0x9b,0xd9,0x08,0x99,0x14};
const char smg6name[] = "Firearms Hero SMG Tactical Base";
const GUID smg7guid = {0xabde7a46,0x7e98,0x4220,0xb8,0x11,0x6a,0xab,0xbb,0xc9,0x78,0x91};
const char smg7name[] = "SMG Tactical +DAMAGE +SKIN01";
const GUID smg8guid = {0xb1cb79d7,0x9960,0x4d5c,0x8b,0x43,0x81,0x21,0x3c,0x85,0x94,0xcd};
const char smg8name[] = "SMG Tactical +STABLE +STEADY AIM +SUPPRESSOR +SKIN03";
const GUID smg9guid = {0xb760b014,0xb7ea,0x41e9,0x9b,0x5c,0x7f,0xed,0x54,0x10,0xb2,0x9b};
const char smg9name[] = "SMG Tactical +HAILSTORM +SKIN01";
const GUID smg10guid = {0xba102d90,0xb8c9,0x47b9,0x97,0xeb,0xb4,0x62,0x34,0x4b,0x46,0xc3};
const char smg10name[] = "SMG Tactical +SKIN01";
const GUID smg11guid = {0xc0f0b9f5,0x965a,0x4205,0x91,0x70,0x34,0xfa,0x67,0x8e,0xad,0x83};
const char smg11name[] = "SMG Tactical +RATE OF FIRE +SKIN01";
const GUID smg12guid = {0xc3fe8e30,0x5a17,0x4881,0xb8,0x82,0xc7,0xf9,0xff,0x19,0x82,0x3c};
const char smg12name[] = "Firearms_Hero_SMG_Fast_Base";
const GUID smg13guid = {0xce8f9c7d,0x7c9c,0x4758,0x83,0xc4,0xda,0x21,0x0f,0x9e,0x0e,0xc4};
const char smg13name[] = "SMG Tactical +STABLE +SKIN01";
const GUID smg14guid = {0xe206ed81,0x0559,0x4289,0x9f,0xec,0xe6,0xa3,0xe9,0xd4,0xee,0x7c};
const char smg14name[] = "SMG01 NPC";
const GUID smg15guid = {0xf66f2a0f,0x2477,0x44c1,0x9e,0xb5,0x5b,0xc5,0xf3,0xb0,0x08,0xa8};
const char smg15name[] = "SMG Tactical +SUPPRESSOR +SKIN01";
const char smg[] = "smg";
#define smgARRLEN 16
guid_name_struct smg_guid_name[smgARRLEN] = {
	(const GUID* const)&smg0guid, (const char* const)&smg0name,
	(const GUID* const)&smg1guid, (const char* const)&smg1name,
	(const GUID* const)&smg2guid, (const char* const)&smg2name,
	(const GUID* const)&smg3guid, (const char* const)&smg3name,
	(const GUID* const)&smg4guid, (const char* const)&smg4name,
	(const GUID* const)&smg5guid, (const char* const)&smg5name,
	(const GUID* const)&smg6guid, (const char* const)&smg6name,
	(const GUID* const)&smg7guid, (const char* const)&smg7name,
	(const GUID* const)&smg8guid, (const char* const)&smg8name,
	(const GUID* const)&smg9guid, (const char* const)&smg9name,
	(const GUID* const)&smg10guid, (const char* const)&smg10name,
	(const GUID* const)&smg11guid, (const char* const)&smg11name,
	(const GUID* const)&smg12guid, (const char* const)&smg12name,
	(const GUID* const)&smg13guid, (const char* const)&smg13name,
	(const GUID* const)&smg14guid, (const char* const)&smg14name,
	(const GUID* const)&smg15guid, (const char* const)&smg15name,
};

const GUID INVALID_CATEGORY_ICON0guid = {0x3c21a38b,0xf33c,0x4665,0x8e,0x01,0xd1,0x4b,0x74,0x31,0x06,0xfb};
const char INVALID_CATEGORY_ICON0name[] = "Pistol Ammo Box B";
const GUID INVALID_CATEGORY_ICON1guid = {0x451659f3,0xc5f3,0x4087,0xbf,0xab,0x04,0x0a,0x3f,0x94,0x29,0x0f};
const char INVALID_CATEGORY_ICON1name[] = "Pistol Ammo Box A";
const GUID INVALID_CATEGORY_ICON2guid = {0x4aae42f5,0xba98,0x4511,0x91,0x57,0xf5,0x25,0xd4,0xa2,0x96,0x7c};
const char INVALID_CATEGORY_ICON2name[] = "Shotgun Ammo Box B";
const GUID INVALID_CATEGORY_ICON3guid = {0x5c93bd5d,0x3025,0x440c,0xb7,0x18,0xc2,0xf7,0xfc,0x5d,0x24,0x69};
const char INVALID_CATEGORY_ICON3name[] = "Shotgun Ammo Box A";
const GUID INVALID_CATEGORY_ICON4guid = {0x5ede75b9,0x6f7e,0x4da3,0x8d,0x5f,0x3d,0x78,0xec,0x87,0x5f,0x64};
const char INVALID_CATEGORY_ICON4name[] = "Sniper Ammo Box B";
const GUID INVALID_CATEGORY_ICON5guid = {0x9e7c4c00,0x7b60,0x4ba2,0xb1,0x07,0xca,0x98,0xd0,0x85,0x21,0x90};
const char INVALID_CATEGORY_ICON5name[] = "Rifle Ammo Box B";
const GUID INVALID_CATEGORY_ICON6guid = {0xbca2ae7a,0x967e,0x4971,0xa0,0x0d,0x69,0x66,0x8f,0xdb,0x15,0xd4};
const char INVALID_CATEGORY_ICON6name[] = "SMG Ammo Box B";
const GUID INVALID_CATEGORY_ICON7guid = {0xc8c697db,0xe103,0x470e,0xbb,0x77,0x67,0xdf,0xd6,0x27,0x59,0xce};
const char INVALID_CATEGORY_ICON7name[] = "Rifle Ammo Box A";
const GUID INVALID_CATEGORY_ICON8guid = {0xdb0e459e,0xeced,0x4b70,0x9f,0x18,0xad,0x13,0xa8,0xd6,0x57,0x14};
const char INVALID_CATEGORY_ICON8name[] = "SMG Ammo Box A";
const GUID INVALID_CATEGORY_ICON9guid = {0xeb3f9a9e,0xd6b2,0x42e9,0xa8,0xd9,0x31,0x75,0x3a,0xb4,0x2e,0x13};
const char INVALID_CATEGORY_ICON9name[] = "Sniper Ammo Box A";
const char INVALID_CATEGORY_ICON[] = "INVALID_CATEGORY_ICON";
#define INVALID_CATEGORY_ICONARRLEN 10
guid_name_struct INVALID_CATEGORY_ICON_guid_name[INVALID_CATEGORY_ICONARRLEN] = {
	(const GUID* const)&INVALID_CATEGORY_ICON0guid, (const char* const)&INVALID_CATEGORY_ICON0name,
	(const GUID* const)&INVALID_CATEGORY_ICON1guid, (const char* const)&INVALID_CATEGORY_ICON1name,
	(const GUID* const)&INVALID_CATEGORY_ICON2guid, (const char* const)&INVALID_CATEGORY_ICON2name,
	(const GUID* const)&INVALID_CATEGORY_ICON3guid, (const char* const)&INVALID_CATEGORY_ICON3name,
	(const GUID* const)&INVALID_CATEGORY_ICON4guid, (const char* const)&INVALID_CATEGORY_ICON4name,
	(const GUID* const)&INVALID_CATEGORY_ICON5guid, (const char* const)&INVALID_CATEGORY_ICON5name,
	(const GUID* const)&INVALID_CATEGORY_ICON6guid, (const char* const)&INVALID_CATEGORY_ICON6name,
	(const GUID* const)&INVALID_CATEGORY_ICON7guid, (const char* const)&INVALID_CATEGORY_ICON7name,
	(const GUID* const)&INVALID_CATEGORY_ICON8guid, (const char* const)&INVALID_CATEGORY_ICON8name,
	(const GUID* const)&INVALID_CATEGORY_ICON9guid, (const char* const)&INVALID_CATEGORY_ICON9name,
};


typedef enum {
	c_melee,
	c_pistol,
	c_tool,
	c_explosives,
	c_sniperrifle,
	c_assaultrifle,
	c_shotgun,
	c_distraction,
	c_poison,
	c_smg,
	c_questitem,
	c_INVALID_CATEGORY_ICON,
} e_class;


typedef struct {
	e_class class_enum;
	const guid_name_struct* const itemrepo;
	size_t len;
	const char* const name;
} itemrepoinfo;
#define allitemreposARRLEN 12
itemrepoinfo air[allitemreposARRLEN] = {
	{c_melee, (const guid_name_struct* const)&melee_guid_name, meleeARRLEN, (const char* const)&melee},
	{c_pistol, (const guid_name_struct* const)&pistol_guid_name, pistolARRLEN, (const char* const)&pistol},
	{c_tool, (const guid_name_struct* const)&tool_guid_name, toolARRLEN, (const char* const)&tool},
	{c_explosives, (const guid_name_struct* const)&explosives_guid_name, explosivesARRLEN, (const char* const)&explosives},
	{c_sniperrifle, (const guid_name_struct* const)&sniperrifle_guid_name, sniperrifleARRLEN, (const char* const)&sniperrifle},
	{c_assaultrifle, (const guid_name_struct* const)&assaultrifle_guid_name, assaultrifleARRLEN, (const char* const)&assaultrifle},
	{c_shotgun, (const guid_name_struct* const)&shotgun_guid_name, shotgunARRLEN, (const char* const)&shotgun},
	{c_distraction, (const guid_name_struct* const)&distraction_guid_name, distractionARRLEN, (const char* const)&distraction},
	{c_poison, (const guid_name_struct* const)&poison_guid_name, poisonARRLEN, (const char* const)&poison},
	{c_smg, (const guid_name_struct* const)&smg_guid_name, smgARRLEN, (const char* const)&smg},
	{c_questitem, (const guid_name_struct* const)&questitem_guid_name, questitemARRLEN, (const char* const)&questitem},
	{c_INVALID_CATEGORY_ICON, (const guid_name_struct* const)&INVALID_CATEGORY_ICON_guid_name, INVALID_CATEGORY_ICONARRLEN, (const char* const)&INVALID_CATEGORY_ICON},
};


//Used to find class from guid
#define LOOPALLITEMS 													\
	for (size_t iter = 0; iter < allitemreposARRLEN; iter++) {			\
		itemrepoinfo* currentclass = &air[iter]; 						\
		for (size_t iter2 = 0; iter2 < air[iter].len; iter2++) {		\
			const guid_name_struct* item = &air[iter].itemrepo[iter2];	\

#define LOOPALLITEMSEND	}}

#define GETPTRTOCLASSARRAY(class) 										\
	for (size_t iter = 0; iter < allitemreposARRLEN; iter++) {			\
		if (air[iter].class_enum != class)								\
			continue;													\
		size_t itemarrlen = air[iter].len;								\
		/*const char* itemtypename = air[iter].name;*/					\
		const guid_name_struct* itemrepo = air[iter].itemrepo; 			\

#define GETPTRTOCLASSARRAYEND break; }


#endif
